/* BHUGOL — the physical land of India, for the Aaj map's physical toggle.
   Coordinates live in the app's 1000x1100 map frame (same frame as the
   Sabhyata anchors), projected from lat/lon by tools of this file's own
   generator comment: x = 187 + 31.7(lon - 72.9), y = 347 + 34.1(28.6 - lat).

   THE MAP LAW HOLDS (CLAUDE.md): every entry is a PLACE — a dot with a
   telling — never a boundary. Landform washes drawn by the renderer are
   elevation and soil, not politics; the outline stays the Survey of India
   depiction, J&K whole. Features across all of J&K as India depicts it are
   included on that basis.

   Facts are Aaj-frame geography: drawn from standard school geography
   (NCERT classes 6-11), Survey of India atlas convention, the MoEF&CC
   protected-area and Ramsar listings, UNESCO listings, and state forest
   and tourism literature. Traditions are framed as tellings. Where a
   superlative is contested, it is hedged. */
window.IND_BHUGOL = {
  sources: ['NCERT geography textbooks (Classes 6\u201311)', 'MoEF&CC / Wildlife Institute of India protected-area listings', 'Ramsar Sites Information Service (India)', 'UNESCO World Heritage listings', 'Survey of India school atlas convention', 'State forest and tourism department literature'],
  types: {
 "river": {
  "n": "River",
  "g": "🌊",
  "c": "#2f6fc4"
 },
 "lake": {
  "n": "Lake",
  "g": "💧",
  "c": "#1f9fd0"
 },
 "wetland": {
  "n": "Wetland & lagoon",
  "g": "🦩",
  "c": "#0fa8a0"
 },
 "falls": {
  "n": "Waterfall",
  "g": "💦",
  "c": "#5b8fd6"
 },
 "park": {
  "n": "National park & sanctuary",
  "g": "🌳",
  "c": "#1fa971"
 },
 "range": {
  "n": "Hills & valleys",
  "g": "⛰️",
  "c": "#9c6b3f"
 },
 "peak": {
  "n": "Mountain peak",
  "g": "🏔️",
  "c": "#6b5cd6"
 },
 "desert": {
  "n": "Desert",
  "g": "🏜️",
  "c": "#d09a3a"
 },
 "glacier": {
  "n": "Glacier",
  "g": "❄️",
  "c": "#7ab3e0"
 },
 "pass": {
  "n": "Mountain pass",
  "g": "🚩",
  "c": "#d94f3d"
 },
 "cave": {
  "n": "Cave & rock",
  "g": "🦇",
  "c": "#7d6a58"
 },
 "island": {
  "n": "Island",
  "g": "🏝️",
  "c": "#0f9f8a"
 },
 "coast": {
  "n": "Coast & beach",
  "g": "🏖️",
  "c": "#e2a51f"
 },
 "spring": {
  "n": "Spring",
  "g": "♨️",
  "c": "#d97748"
 }
},
  features: [
  {"id": "dal-lake-jk", "n": "Dal Lake", "st": "JK", "t": "lake", "x": 249.4, "y": 158.8, "f": "Srinagar’s mirror — houseboats, floating vegetable gardens and shikaras have lived on this lake for centuries."},
  {"id": "wular-lake-jk", "n": "Wular Lake", "st": "JK", "t": "lake", "x": 240.9, "y": 150.6, "f": "One of Asia’s largest freshwater lakes, swelling and shrinking with the Jhelum — a sponge that softens Kashmir’s floods."},
  {"id": "jhelum-river-jk", "n": "Jhelum River", "st": "JK", "t": "river", "x": 247.2, "y": 156.0, "f": "The river of the Kashmir Valley — it loops lazily through Srinagar under old wooden bridges before cutting through the mountains."},
  {"id": "chenab-river-jk", "n": "Chenab River", "st": "JK", "t": "river", "x": 263.1, "y": 193.5, "f": "The “moon river” (chandra-bhaga) — born of two Himachal streams, it thunders through gorges so deep the world’s highest railway bridge crosses one."},
  {"id": "pir-panjal-range-jk", "n": "Pir Panjal Range", "st": "JK", "t": "range", "x": 240.9, "y": 179.9, "f": "The long wall between the Kashmir Valley and the plains — its tunnels and passes are the valley’s doorways."},
  {"id": "zoji-la-jk", "n": "Zoji La", "st": "JK", "t": "pass", "x": 268.5, "y": 153.3, "f": "The gate between Kashmir and Ladakh — snow shuts it for months, and its hairpins hang over sheer drops."},
  {"id": "gulmarg-jk", "n": "Gulmarg", "st": "JK", "t": "range", "x": 233.9, "y": 161.2, "f": "The “meadow of flowers” — wildflower slopes in summer, and one of the world’s highest cable-car rides up Apharwat in winter."},
  {"id": "dachigam-national-park-jk", "n": "Dachigam National Park", "st": "JK", "t": "park", "x": 254.2, "y": 158.4, "f": "The last true home of the hangul, Kashmir’s own red deer — barely a couple of hundred remain."},
  {"id": "amarnath-cave-jk", "n": "Amarnath Cave", "st": "JK", "t": "cave", "x": 269.4, "y": 155.7, "f": "A high Himalayan cave where an ice stalagmite forms each summer — lakhs of pilgrims walk days to see it."},
  {"id": "verinag-spring-jk", "n": "Verinag Spring", "st": "JK", "t": "spring", "x": 261.5, "y": 178.2, "f": "An octagonal blue-green spring built round by Jahangir — honoured as the source of the Jhelum."},
  {"id": "kishtwar-national-park-jk", "n": "Kishtwar National Park", "st": "JK", "t": "park", "x": 278.9, "y": 176.5, "f": "Steep cold wilderness of the upper Chenab — snow leopards, ibex and brown bears keep to its heights."},
  {"id": "mansar-lake-jk", "n": "Mansar Lake", "st": "JK", "t": "lake", "x": 258.3, "y": 207.2, "f": "A forest-ringed lake near Jammu, tied by tradition to the Mahabharata and busy with turtles."},
  {"id": "pangong-tso-la", "n": "Pangong Tso", "st": "LA", "t": "lake", "x": 367.7, "y": 171.0, "f": "A salt lake at 4,200 m that changes colour through the day — blue to green to gold — and freezes solid though it is salty."},
  {"id": "tso-moriri-la", "n": "Tso Moriri", "st": "LA", "t": "lake", "x": 358.2, "y": 200.4, "f": "A high, still lake ringed by 6,000 m peaks — black-necked cranes nest on its shores."},
  {"id": "khardung-la-la", "n": "Khardung La", "st": "LA", "t": "pass", "x": 336.0, "y": 153.3, "f": "One of the world’s highest roads a truck can cross — prayer flags snap in the thin air on top."},
  {"id": "siachen-glacier-la", "n": "Siachen Glacier", "st": "LA", "t": "glacier", "x": 320.1, "y": 115.1, "f": "Among the longest glaciers outside the polar regions — a river of ice high in the Karakoram."},
  {"id": "indus-river-la", "n": "Indus River", "st": "LA", "t": "river", "x": 335.4, "y": 157.4, "f": "The river that named India itself runs right past Leh — grey with glacier flour, older than the mountains it cuts."},
  {"id": "zanskar-river-la", "n": "Zanskar River", "st": "LA", "t": "river", "x": 317.0, "y": 166.3, "f": "In deepest winter it freezes into the Chadar — a sheet of ice that becomes the only road to Zanskar’s villages."},
  {"id": "nubra-valley-la", "n": "Nubra Valley", "st": "LA", "t": "range", "x": 336.0, "y": 142.4, "f": "A high desert valley of sand dunes and double-humped Bactrian camels — leftovers of the old Silk Road caravans."},
  {"id": "hemis-national-park-la", "n": "Hemis National Park", "st": "LA", "t": "park", "x": 332.8, "y": 166.3, "f": "India’s great snow-leopard country — the grey ghost of the mountains is seen here more than almost anywhere on Earth."},
  {"id": "saser-kangri-la", "n": "Saser Kangri", "st": "LA", "t": "peak", "x": 340.7, "y": 133.2, "f": "The crown of the Saser range in the eastern Karakoram — among the highest peaks entirely within Ladakh."},
  {"id": "k2-la", "n": "K2", "st": "LA", "t": "peak", "x": 301.4, "y": 98.8, "f": "The world’s second-highest mountain, in the Karakoram — steeper and stormier than Everest, climbers call it the Savage Mountain."},
  {"id": "lamayuru-moonland-la", "n": "Lamayuru Moonland", "st": "LA", "t": "range", "x": 309.7, "y": 153.3, "f": "Wind and water carved these pale badlands so strangely that everyone calls them the Moonland."},
  {"id": "drass-la", "n": "Drass", "st": "LA", "t": "range", "x": 277.3, "y": 148.2, "f": "One of the coldest inhabited places on Earth — winter here has dropped below minus 40."},
  {"id": "rohtang-pass-hp", "n": "Rohtang Pass", "st": "HP", "t": "pass", "x": 324.9, "y": 218.4, "f": "The old gateway from Kullu to Lahaul — its name means “pile of bones”, for the winters that once trapped travellers."},
  {"id": "great-himalayan-national-park-hp", "n": "Great Himalayan National Park", "st": "HP", "t": "park", "x": 332.8, "y": 241.3, "f": "A UNESCO World Heritage wilderness — western tragopans call at dawn and no road enters it."},
  {"id": "khajjiar-hp", "n": "Khajjiar", "st": "HP", "t": "range", "x": 287.2, "y": 212.3, "f": "A green saucer of meadow ringed by deodars — travellers have long called it a little Switzerland."},
  {"id": "beas-river-hp", "n": "Beas River", "st": "HP", "t": "river", "x": 320.1, "y": 231.1, "f": "Rises at Rohtang and races through Kullu and Manali — the river Alexander’s army refused to cross, the old accounts say."},
  {"id": "sutlej-river-hp", "n": "Sutlej River", "st": "HP", "t": "river", "x": 317.0, "y": 254.9, "f": "The longest of Punjab’s five rivers — it starts in Tibet and saws clean through the Himalaya."},
  {"id": "chandratal-hp", "n": "Chandratal", "st": "HP", "t": "lake", "x": 336.6, "y": 214.7, "f": "The crescent “moon lake” of Spiti at 4,300 m — its water shifts colour as the sky moves."},
  {"id": "renuka-lake-hp", "n": "Renuka Lake", "st": "HP", "t": "lake", "x": 331.2, "y": 278.8, "f": "Himachal’s largest natural lake, shaped — the tellings say — like the goddess Renuka sleeping."},
  {"id": "spiti-valley-hp", "n": "Spiti Valley", "st": "HP", "t": "range", "x": 349.6, "y": 222.5, "f": "A cold high desert of mud-brick villages and thousand-year monasteries — “the middle land” between India and Tibet."},
  {"id": "kinner-kailash-hp", "n": "Kinner Kailash", "st": "HP", "t": "peak", "x": 358.2, "y": 248.1, "f": "Kinnaur’s sacred peak — a rock pillar near its summit is honoured as Shiva’s own."},
  {"id": "dhauladhar-range-hp", "n": "Dhauladhar Range", "st": "HP", "t": "range", "x": 297.9, "y": 224.2, "f": "The “white ridge” that stands straight up behind Dharamshala — snow on top, tea gardens at its feet."},
  {"id": "shivalik-hills-hp", "n": "Shivalik Hills", "st": "HP", "t": "range", "x": 320.1, "y": 268.6, "f": "The Himalaya’s youngest, lowest step — soft hills of river-borne gravel where fossils of ancient elephants turn up."},
  {"id": "pin-valley-national-park-hp", "n": "Pin Valley National Park", "st": "HP", "t": "park", "x": 342.3, "y": 234.5, "f": "Spiti’s stark park of ibex and snow leopards, where the treeline gives up and rock takes over."},
  {"id": "jogini-falls-hp", "n": "Jogini Falls", "st": "HP", "t": "falls", "x": 323.0, "y": 221.5, "f": "A waterfall above Vashisht sacred to the local devi — pilgrims and picnickers share the path."},
  {"id": "baralacha-la-hp", "n": "Baralacha La", "st": "HP", "t": "pass", "x": 330.6, "y": 205.5, "f": "A 4,800 m crossroads pass where roads from Ladakh, Lahaul and Spiti meet in the snow."},
  {"id": "manimahesh-lake-hp", "n": "Manimahesh Lake", "st": "HP", "t": "lake", "x": 305.9, "y": 217.4, "f": "A high sacred lake below Manimahesh Kailash — thousands walk up for a dip at the yatra each year."},
  {"id": "sutlej-plains-pb", "n": "Sutlej (plains)", "st": "PB", "t": "river", "x": 253.6, "y": 268.6, "f": "Punjab’s workhorse river — its canals, cut over a century and a half, water the fields that feed India."},
  {"id": "beas-plains-pb", "n": "Beas (plains)", "st": "PB", "t": "river", "x": 263.1, "y": 248.1, "f": "Joins the Sutlej at Harike after its mountain run — together they make the southern of Punjab’s great streams."},
  {"id": "ravi-river-pb", "n": "Ravi River", "st": "PB", "t": "river", "x": 253.6, "y": 231.1, "f": "The river of Lahore and Amritsar’s north — one of the five that give Punjab (“five waters”) its name."},
  {"id": "harike-wetland-pb", "n": "Harike Wetland", "st": "PB", "t": "wetland", "x": 259.9, "y": 259.4, "f": "Where Beas meets Sutlej spreads north India’s biggest wetland — tens of thousands of winter birds, even Indus river dolphins."},
  {"id": "kanjli-wetland-pb", "n": "Kanjli Wetland", "st": "PB", "t": "wetland", "x": 266.2, "y": 251.5, "f": "A Ramsar wetland on the little Kali Bein — quiet water thick with birds."},
  {"id": "kali-bein-pb", "n": "Kali Bein", "st": "PB", "t": "river", "x": 269.4, "y": 249.8, "f": "The stream where, tradition says, Guru Nanak disappeared for three days and rose with his message — lovingly cleaned by volunteers."},
  {"id": "ropar-wetland-pb", "n": "Ropar Wetland", "st": "PB", "t": "wetland", "x": 301.1, "y": 266.2, "f": "Where the Sutlej leaves the hills — a Ramsar site beside one of the oldest headworks in India."},
  {"id": "ranjit-sagar-lake-pb", "n": "Ranjit Sagar Lake", "st": "PB", "t": "lake", "x": 276.7, "y": 216.1, "f": "The great reservoir on the Ravi — a sea in the Shivalik foothills."},
  {"id": "shivalik-foothills-pb", "n": "Shivalik Foothills", "st": "PB", "t": "range", "x": 297.9, "y": 272.0, "f": "Punjab’s only hills — a low wooded fringe where the plains finally ripple."},
  {"id": "abohar-sanctuary-pb", "n": "Abohar Sanctuary", "st": "PB", "t": "park", "x": 228.2, "y": 295.9, "f": "An open-field sanctuary where blackbuck bound through farmland — protected by the Bishnoi villages’ own old promise to wildlife."},
  {"id": "ghaggar-river-pb", "n": "Ghaggar River", "st": "PB", "t": "river", "x": 244.1, "y": 302.7, "f": "A seasonal river that fades into the desert — many scholars link its dry bed to the Sarasvati of the old hymns, and argue about it happily."},
  {"id": "bir-moti-bagh-sanctuary-pb", "n": "Bir Moti Bagh Sanctuary", "st": "PB", "t": "park", "x": 297.9, "y": 289.0, "f": "One of the old princely “bir” hunting groves of Patiala, now a sanctuary where blackbuck graze."},
  {"id": "yamuna-haryana-hr", "n": "Yamuna (Haryana)", "st": "HR", "t": "river", "x": 320.1, "y": 302.7, "f": "Enters the plains at Hathnikund — its canals, dug from Mughal times onward, green half of Haryana."},
  {"id": "sultanpur-national-park-hr", "n": "Sultanpur National Park", "st": "HR", "t": "park", "x": 313.8, "y": 351.8, "f": "A little lake park an hour from Delhi where winter brings painted storks, pelicans and flamingos by the thousand."},
  {"id": "kalesar-national-park-hr", "n": "Kalesar National Park", "st": "HR", "t": "park", "x": 332.8, "y": 287.3, "f": "Haryana’s sal-forest corner in the Shivaliks — leopards, and elephants passing through from the hills."},
  {"id": "morni-hills-hr", "n": "Morni Hills", "st": "HR", "t": "range", "x": 319.2, "y": 275.4, "f": "Haryana’s only hill station — pine slopes and two small lakes the locals say are linked underground."},
  {"id": "aravalli-edge-hr", "n": "Aravalli Edge", "st": "HR", "t": "range", "x": 313.8, "y": 357.2, "f": "The worn northern knuckles of one of Earth’s oldest mountain ranges peter out here and in Delhi."},
  {"id": "badkhal-lake-hr", "n": "Badkhal Lake", "st": "HR", "t": "lake", "x": 326.5, "y": 353.1, "f": "A natural lake against the Aravallis — it dried as groundwater fell and is being coaxed back to life."},
  {"id": "brahma-sarovar-hr", "n": "Brahma Sarovar", "st": "HR", "t": "lake", "x": 311.6, "y": 300.6, "f": "Kurukshetra’s vast sacred tank — at Gita Jayanti its waters are ringed by a million lamps."},
  {"id": "damdama-lake-hr", "n": "Damdama Lake", "st": "HR", "t": "lake", "x": 320.1, "y": 357.2, "f": "A monsoon-fed lake in the Aravalli folds — one of the bigger natural sheets of water near the capital."},
  {"id": "bhindawas-wetland-hr", "n": "Bhindawas Wetland", "st": "HR", "t": "wetland", "x": 302.7, "y": 349.4, "f": "Haryana’s largest wetland sanctuary — a Ramsar refuge ringed by a walking bund."},
  {"id": "ghaggar-haryana-hr", "n": "Ghaggar (Haryana)", "st": "HR", "t": "river", "x": 253.6, "y": 312.9, "f": "The seasonal river of Haryana’s northwest — along its old banks sit some of the oldest Harappan villages known."},
  {"id": "nanda-devi-uk", "n": "Nanda Devi", "st": "UK", "t": "peak", "x": 411.1, "y": 286.6, "f": "The highest peak standing fully inside India (7,816 m) — the “bliss-giving goddess”, ringed by a wall of guardian peaks."},
  {"id": "gangotri-glacier-uk", "n": "Gangotri Glacier", "st": "UK", "t": "glacier", "x": 382.9, "y": 267.9, "f": "From its snout at Gaumukh — “the cow’s mouth” — the ice melts into the stream that becomes the Ganga."},
  {"id": "yamunotri-uk", "n": "Yamunotri", "st": "UK", "t": "glacier", "x": 362.9, "y": 264.8, "f": "The Yamuna is born in these snows below Bandarpunch — a hot spring beside the temple cooks pilgrims’ rice in a cloth."},
  {"id": "valley-of-flowers-uk", "n": "Valley of Flowers", "st": "UK", "t": "park", "x": 399.4, "y": 274.4, "f": "A UNESCO valley that erupts into hundreds of kinds of wildflower every monsoon — found by lost climbers in 1931."},
  {"id": "jim-corbett-national-park-uk", "n": "Jim Corbett National Park", "st": "UK", "t": "park", "x": 373.1, "y": 315.3, "f": "India’s first national park (1936) — where Project Tiger itself began in 1973."},
  {"id": "rajaji-national-park-uk", "n": "Rajaji National Park", "st": "UK", "t": "park", "x": 355.0, "y": 297.6, "f": "Sal forests at the Ganga’s gateway to the plains — elephant herds cross the river here as they always have."},
  {"id": "nainital-lake-uk", "n": "Nainital Lake", "st": "UK", "t": "lake", "x": 394.6, "y": 320.4, "f": "The emerald eye-shaped lake that named the town — one of a chain of lakes cupped in the Kumaon hills."},
  {"id": "bhimtal-uk", "n": "Bhimtal", "st": "UK", "t": "lake", "x": 397.8, "y": 321.4, "f": "Kumaon’s largest lake, with an island at its middle — quieter cousin of Nainital."},
  {"id": "kempty-falls-uk", "n": "Kempty Falls", "st": "UK", "t": "falls", "x": 349.6, "y": 282.6, "f": "Mussoorie’s crowd-pleaser cascade, splashing down since the British picnicked under it in the 1830s."},
  {"id": "alaknanda-river-uk", "n": "Alaknanda River", "st": "UK", "t": "river", "x": 375.6, "y": 294.1, "f": "The Ganga’s wilder parent stream — it gathers four sacred confluences on its run from Badrinath."},
  {"id": "bhagirathi-river-uk", "n": "Bhagirathi River", "st": "UK", "t": "river", "x": 364.5, "y": 275.4, "f": "The Ganga’s other parent, named for the king whose penance — the story goes — brought her down from heaven."},
  {"id": "devprayag-uk", "n": "Devprayag", "st": "UK", "t": "river", "x": 367.7, "y": 294.1, "f": "Where Alaknanda and Bhagirathi braid into one — and the river is finally called Ganga."},
  {"id": "trishul-uk", "n": "Trishul", "st": "UK", "t": "peak", "x": 404.8, "y": 288.7, "f": "Three summits in a line like Shiva’s trident — in 1907 it was the first 7,000 m peak ever climbed."},
  {"id": "chaukhamba-uk", "n": "Chaukhamba", "st": "UK", "t": "peak", "x": 389.9, "y": 273.7, "f": "“Four pillars” — the massif whose snows feed the Gangotri glacier, filling the skyline above Badrinath."},
  {"id": "mussoorie-ridge-uk", "n": "Mussoorie Ridge", "st": "UK", "t": "range", "x": 350.9, "y": 283.6, "f": "The “Queen of the Hills” rides a long green ridge — from its edge the plains fall away like a map."},
  {"id": "tehri-lake-uk", "n": "Tehri Lake", "st": "UK", "t": "lake", "x": 363.9, "y": 286.3, "f": "The vast reservoir behind one of the world’s tallest earth dams — old Tehri town sleeps beneath it."},
  {"id": "sangam-prayagraj-up", "n": "Sangam, Prayagraj", "st": "UP", "t": "river", "x": 471.7, "y": 455.4, "f": "Where the Ganga and Yamuna visibly meet — brown water folding into blue — and the Kumbh gathers the largest crowds on Earth."},
  {"id": "yamuna-up-up", "n": "Yamuna (UP)", "st": "UP", "t": "river", "x": 348.7, "y": 394.7, "f": "Delhi’s and Agra’s river — the Taj was set on its bank so the marble could stand in its mirror."},
  {"id": "ghaghara-river-up", "n": "Ghaghara River", "st": "UP", "t": "river", "x": 481.8, "y": 408.4, "f": "The Ganga’s biggest tributary by water — at Ayodhya it flows as the Sarayu of the Ramayana tellings."},
  {"id": "gomti-river-up", "n": "Gomti River", "st": "UP", "t": "river", "x": 442.2, "y": 406.7, "f": "Lucknow’s slow river, rising not in mountains but in a plains lake — a groundwater child."},
  {"id": "chambal-ravines-up", "n": "Chambal Ravines", "st": "UP", "t": "river", "x": 380.4, "y": 415.2, "f": "The Chambal’s badland maze — so long feared for dacoits that the river stayed clean enough for gharials and dolphins."},
  {"id": "dudhwa-national-park-up", "n": "Dudhwa National Park", "st": "UP", "t": "park", "x": 434.3, "y": 350.4, "f": "Terai grasslands on the Nepal border — tigers, swamp deer, and rhinos brought back in 1984 after a century away."},
  {"id": "national-chambal-sanctuary-up", "n": "National Chambal Sanctuary", "st": "UP", "t": "park", "x": 377.2, "y": 411.8, "f": "The gharial’s stronghold — that thin-snouted, fish-eating crocodile survives mostly in this one river."},
  {"id": "okhla-bird-sanctuary-up", "n": "Okhla Bird Sanctuary", "st": "UP", "t": "wetland", "x": 326.8, "y": 348.7, "f": "A barrage on the Yamuna where the city ends and thousands of winter ducks begin."},
  {"id": "vindhya-at-mirzapur-up", "n": "Vindhya at Mirzapur", "st": "UP", "t": "range", "x": 494.5, "y": 466.4, "f": "The Vindhya scarp steps down to the Ganga here — the old northern rim of the Deccan world."},
  {"id": "betwa-river-up", "n": "Betwa River", "st": "UP", "t": "river", "x": 415.2, "y": 439.1, "f": "A granite-bedded Bundelkhand river that joins the Yamuna — its old name Vetravati means “full of reeds”."},
  {"id": "bakhira-wetland-up", "n": "Bakhira Wetland", "st": "UP", "t": "wetland", "x": 510.3, "y": 405.0, "f": "Eastern UP’s great bird lake — a Ramsar site loud with winter wings."},
  {"id": "hastinapur-sanctuary-up", "n": "Hastinapur Sanctuary", "st": "UP", "t": "park", "x": 348.7, "y": 329.9, "f": "Khadar floodplain of the Ganga where swamp deer and gharial hold on — around the epic’s own old capital."},
  {"id": "ganga-at-patna-br", "n": "Ganga at Patna", "st": "BR", "t": "river", "x": 573.7, "y": 449.3, "f": "Already a kilometre wide here — the river that carries north India past the old capital of empires."},
  {"id": "kosi-river-br", "n": "Kosi River", "st": "BR", "t": "river", "x": 630.8, "y": 439.1, "f": "The “sorrow of Bihar” — it swings across its own fan of silt, and has shifted its bed by over a hundred kilometres in two centuries."},
  {"id": "gandak-river-br", "n": "Gandak River", "st": "BR", "t": "river", "x": 567.4, "y": 428.8, "f": "Comes down from Nepal carrying the smooth black shaligram stones that many households keep as sacred."},
  {"id": "son-river-br", "n": "Son River", "st": "BR", "t": "river", "x": 538.9, "y": 476.6, "f": "The Ganga’s great southern tributary — its wide golden sands gave it the name “Son”, gold."},
  {"id": "valmiki-national-park-br", "n": "Valmiki National Park", "st": "BR", "t": "park", "x": 542.0, "y": 391.3, "f": "Bihar’s tiger forest in the Himalayan foothills — named for the sage whose ashram tradition places nearby."},
  {"id": "kabartal-wetland-br", "n": "Kabartal Wetland", "st": "BR", "t": "wetland", "x": 607.0, "y": 449.3, "f": "Bihar’s first Ramsar site — a vast floodplain marsh that fills and empties with the Ganga’s moods."},
  {"id": "rajgir-hills-br", "n": "Rajgir Hills", "st": "BR", "t": "range", "x": 583.9, "y": 468.7, "f": "Five ancient hills that once ringed the first capital of Magadha — the Buddha walked these paths."},
  {"id": "rajgir-hot-springs-br", "n": "Rajgir Hot Springs", "st": "BR", "t": "spring", "x": 583.9, "y": 469.1, "f": "Warm water rises through the old rock at Brahmakund — pilgrims have bathed here for thousands of years."},
  {"id": "barabar-caves-br", "n": "Barabar Caves", "st": "BR", "t": "cave", "x": 572.5, "y": 469.8, "f": "India’s oldest rock-cut caves, polished to a mirror inside by Mauryan masons — clap once and the echo sings."},
  {"id": "kakolat-falls-br", "n": "Kakolat Falls", "st": "BR", "t": "falls", "x": 589.6, "y": 485.1, "f": "A green plunge pool below a curtain of water — the tellings say a cursed king lived here as a serpent till the water freed him."},
  {"id": "hundru-falls-jh", "n": "Hundru Falls", "st": "JH", "t": "falls", "x": 591.8, "y": 522.6, "f": "The Subarnarekha leaps ninety-eight metres off the Chotanagpur edge — Jharkhand’s thundering signature."},
  {"id": "lodh-falls-jh", "n": "Lodh Falls", "st": "JH", "t": "falls", "x": 539.5, "y": 521.6, "f": "Jharkhand’s tallest waterfall — heard through the sal forest long before it is seen."},
  {"id": "dassam-falls-jh", "n": "Dassam Falls", "st": "JH", "t": "falls", "x": 585.5, "y": 533.2, "f": "The Kanchi river fans over a wide rock staircase — locals call the ten streams its ten braids."},
  {"id": "betla-national-park-jh", "n": "Betla National Park", "st": "JH", "t": "park", "x": 544.9, "y": 508.3, "f": "One of India’s first tiger reserves — elephants, old fort ruins and sal forest together."},
  {"id": "parasnath-hill-jh", "n": "Parasnath Hill", "st": "JH", "t": "peak", "x": 607.3, "y": 505.2, "f": "Jharkhand’s highest point — as Shikharji, the holiest of Jain pilgrimages, where twenty tirthankaras attained liberation, as the tradition holds."},
  {"id": "netarhat-plateau-jh", "n": "Netarhat Plateau", "st": "JH", "t": "range", "x": 547.4, "y": 521.6, "f": "The “Queen of Chotanagpur” — pine-cool sunrise country on the plateau’s western rim."},
  {"id": "damodar-river-jh", "n": "Damodar River", "st": "JH", "t": "river", "x": 605.4, "y": 517.5, "f": "Once cursed as Bengal’s “river of sorrow” for its floods — now strung with the dams that tamed it."},
  {"id": "subarnarekha-river-jh", "n": "Subarnarekha River", "st": "JH", "t": "river", "x": 608.6, "y": 527.7, "f": "“Streak of gold” — grains of real gold wash down its sands, panned by villagers for generations."},
  {"id": "chotanagpur-plateau-jh", "n": "Chotanagpur Plateau", "st": "JH", "t": "range", "x": 580.1, "y": 524.3, "f": "A mineral treasure-chest of a plateau — coal, iron, mica and copper that built industrial India."},
  {"id": "hazaribagh-sanctuary-jh", "n": "Hazaribagh Sanctuary", "st": "JH", "t": "park", "x": 583.2, "y": 503.9, "f": "Rolling sal country of “a thousand gardens” — sambar and nilgai in old hunting grounds turned refuge."},
  {"id": "dimna-lake-jh", "n": "Dimna Lake", "st": "JH", "t": "lake", "x": 611.8, "y": 542.1, "f": "A blue reservoir under Dalma hill, dug for Jamshedpur — elephants come down to its shores."},
  {"id": "dalma-sanctuary-jh", "n": "Dalma Sanctuary", "st": "JH", "t": "park", "x": 608.6, "y": 541.4, "f": "The elephants’ own hills above Jamshedpur — herds cross to Bengal on paths older than the city below."},
  {"id": "sundarbans-wb", "n": "Sundarbans", "st": "WB", "t": "park", "x": 694.2, "y": 573.8, "f": "The largest mangrove forest on Earth — the only mangroves anywhere with tigers, who swim its channels."},
  {"id": "hooghly-river-wb", "n": "Hooghly River", "st": "WB", "t": "river", "x": 676.8, "y": 551.6, "f": "The Ganga’s western arm to the sea — Kolkata’s river of ghats, ferries and the great bridge."},
  {"id": "teesta-river-wb", "n": "Teesta River", "st": "WB", "t": "river", "x": 678.3, "y": 405.0, "f": "The green river of the northern hills — it drains Sikkim and stitches the Darjeeling country to the plains."},
  {"id": "darjeeling-ridge-wb", "n": "Darjeeling Ridge", "st": "WB", "t": "range", "x": 673.9, "y": 400.2, "f": "Tea gardens on a Himalayan balcony — on clear mornings Kangchenjunga fills half the sky."},
  {"id": "sandakphu-wb", "n": "Sandakphu", "st": "WB", "t": "peak", "x": 665.7, "y": 397.8, "f": "Bengal’s highest point — from its top you can see four of the five highest mountains on Earth in one sweep."},
  {"id": "singalila-national-park-wb", "n": "Singalila National Park", "st": "WB", "t": "park", "x": 667.3, "y": 398.1, "f": "The red panda’s ridge-top forest on the Nepal border — rhododendrons in fire-colours each spring."},
  {"id": "neora-valley-national-park-wb", "n": "Neora Valley National Park", "st": "WB", "t": "park", "x": 687.9, "y": 399.2, "f": "One of the last untouched forests of the eastern Himalaya — so dense parts of it have never been properly explored."},
  {"id": "jaldapara-national-park-wb", "n": "Jaldapara National Park", "st": "WB", "t": "park", "x": 706.2, "y": 411.8, "f": "Tall-grass country under the hills — Bengal’s stronghold of the one-horned rhinoceros."},
  {"id": "buxa-tiger-reserve-wb", "n": "Buxa Tiger Reserve", "st": "WB", "t": "park", "x": 716.4, "y": 410.1, "f": "Forests around an old hill fort where freedom fighters were once jailed — elephants rule the roads at dusk."},
  {"id": "gorumara-national-park-wb", "n": "Gorumara National Park", "st": "WB", "t": "park", "x": 691.0, "y": 411.8, "f": "A small park with a big cast — rhinos, elephants, bison and peacocks around every watchtower."},
  {"id": "digha-wb", "n": "Digha", "st": "WB", "t": "coast", "x": 650.1, "y": 584.7, "f": "Bengal’s own seaside — a long low beach where the Bay of Bengal comes in flat and warm."},
  {"id": "ganga-delta-wb", "n": "Ganga Delta", "st": "WB", "t": "wetland", "x": 675.2, "y": 575.5, "f": "The world’s largest delta, shared with Bangladesh — land and water swap places here with every tide."},
  {"id": "mirik-lake-wb", "n": "Mirik Lake", "st": "WB", "t": "lake", "x": 671.7, "y": 405.3, "f": "A hill lake among orange orchards and cardamom — rowing boats under Kanchenjunga light."},
  {"id": "damodar-bengal-wb", "n": "Damodar (Bengal)", "st": "WB", "t": "river", "x": 643.5, "y": 520.9, "f": "The plateau river that powers Bengal’s coal country before joining the Hooghly."},
  {"id": "kangchenjunga-sk", "n": "Kangchenjunga", "st": "SK", "t": "peak", "x": 670.4, "y": 377.7, "f": "The third-highest mountain on Earth (8,586 m) — Sikkim honours it as a guardian deity, so climbers stop short of the very summit."},
  {"id": "khangchendzonga-national-park-sk", "n": "Khangchendzonga National Park", "st": "SK", "t": "park", "x": 675.2, "y": 377.7, "f": "A UNESCO site honoured for nature AND sacred culture together — glaciers, forests and holy peaks in one park."},
  {"id": "tsomgo-lake-sk", "n": "Tsomgo Lake", "st": "SK", "t": "lake", "x": 689.8, "y": 388.9, "f": "A sacred lake at 3,750 m that freezes white in winter — lamas once read its colours to tell the year ahead."},
  {"id": "gurudongmar-lake-sk", "n": "Gurudongmar Lake", "st": "SK", "t": "lake", "x": 688.2, "y": 366.8, "f": "One of the highest lakes in the world (5,430 m) — blessed, the tellings say, so one corner never freezes."},
  {"id": "nathu-la-sk", "n": "Nathu La", "st": "SK", "t": "pass", "x": 692.0, "y": 388.3, "f": "The old Silk Route pass to Tibet — mule caravans crossed here for centuries; border trade returned in 2006."},
  {"id": "teesta-sikkim-sk", "n": "Teesta (Sikkim)", "st": "SK", "t": "river", "x": 684.7, "y": 391.3, "f": "Sikkim’s mother river, milk-green with glacier flour, crashing down two vertical kilometres in one small state."},
  {"id": "yumthang-valley-sk", "n": "Yumthang Valley", "st": "SK", "t": "range", "x": 687.9, "y": 374.3, "f": "Sikkim’s valley of flowers — a rhododendron sanctuary where whole hillsides bloom at once."},
  {"id": "zemu-glacier-sk", "n": "Zemu Glacier", "st": "SK", "t": "glacier", "x": 673.6, "y": 376.7, "f": "The largest glacier of the eastern Himalaya — the Teesta is born of its melt."},
  {"id": "seven-sisters-falls-sk", "n": "Seven Sisters Falls", "st": "SK", "t": "falls", "x": 686.6, "y": 387.9, "f": "Seven silver threads on one cliff face beside the North Sikkim highway — best after rain, when all seven roar."},
  {"id": "khecheopalri-lake-sk", "n": "Khecheopalri Lake", "st": "SK", "t": "lake", "x": 672.0, "y": 389.6, "f": "A wishing lake sacred to Buddhists and Hindus alike — the tellings say birds pick every fallen leaf off its surface."},
  {"id": "namdapha-national-park-ar", "n": "Namdapha National Park", "st": "AR", "t": "park", "x": 931.9, "y": 384.5, "f": "India’s easternmost park, climbing from steamy rainforest to snow — tiger, leopard, clouded leopard and snow leopard in ONE park."},
  {"id": "sela-pass-ar", "n": "Sela Pass", "st": "AR", "t": "pass", "x": 795.6, "y": 384.5, "f": "The high road to Tawang at 4,170 m — a sacred lake sits beside the pass in the snowfields."},
  {"id": "sangetsar-lake-ar", "n": "Sangetsar Lake", "st": "AR", "t": "lake", "x": 791.8, "y": 380.4, "f": "Born of an earthquake in 1950 — dead pines still stand in its water like masts."},
  {"id": "kangto-ar", "n": "Kangto", "st": "AR", "t": "peak", "x": 809.3, "y": 372.2, "f": "Arunachal’s highest peak, riding the crest line above the clouds on the Tibet border."},
  {"id": "siang-river-ar", "n": "Siang River", "st": "AR", "t": "river", "x": 887.6, "y": 364.1, "f": "The Brahmaputra’s entry into India — after a 2,900 km run across Tibet as the Tsangpo, it barrels through gorges here."},
  {"id": "lohit-river-ar", "n": "Lohit River", "st": "AR", "t": "river", "x": 925.6, "y": 374.3, "f": "The “river of blood” — named for its red flood silt — meets the Siang to help make the Brahmaputra."},
  {"id": "subansiri-river-ar", "n": "Subansiri River", "st": "AR", "t": "river", "x": 865.4, "y": 381.1, "f": "The Brahmaputra’s largest tributary — its name means “gold-flowing”, for the dust once panned from it."},
  {"id": "ziro-valley-ar", "n": "Ziro Valley", "st": "AR", "t": "range", "x": 850.5, "y": 383.1, "f": "The Apatani people’s valley of wet rice fields farmed without a single plough animal — a marvel of careful water."},
  {"id": "mouling-national-park-ar", "n": "Mouling National Park", "st": "AR", "t": "park", "x": 890.7, "y": 350.4, "f": "Cloud forest so remote that new species keep walking into camera traps."},
  {"id": "nuranang-falls-ar", "n": "Nuranang Falls", "st": "AR", "t": "falls", "x": 794.1, "y": 382.8, "f": "A hundred-metre white wall near Tawang — it appears out of pine forest almost without warning."},
  {"id": "dibang-valley-ar", "n": "Dibang Valley", "st": "AR", "t": "range", "x": 909.8, "y": 343.6, "f": "India’s emptiest district by people — and one of its fullest by wilderness; the Idu Mishmi keep its old ways."},
  {"id": "dz-kou-valley-nl", "n": "Dzükou Valley", "st": "NL", "t": "range", "x": 858.1, "y": 450.3, "f": "A rolling green valley above the clouds famous for the Dzükou lily, which grows nowhere else on Earth."},
  {"id": "mount-saramati-nl", "n": "Mount Saramati", "st": "NL", "t": "peak", "x": 888.5, "y": 444.9, "f": "Nagaland’s rooftop on the Myanmar border — villagers of Thanamir keep the climbing trail."},
  {"id": "japf-peak-nl", "n": "Japfü Peak", "st": "NL", "t": "peak", "x": 859.0, "y": 449.3, "f": "Second-highest in Nagaland — home to giant rhododendron trees taller than houses."},
  {"id": "ntangki-national-park-nl", "n": "Ntangki National Park", "st": "NL", "t": "park", "x": 843.2, "y": 452.7, "f": "Forest of hoolock gibbons — the only apes found in India, singing at dawn."},
  {"id": "doyang-river-nl", "n": "Doyang River", "st": "NL", "t": "river", "x": 863.8, "y": 428.8, "f": "Each autumn its reservoir hosts lakhs of Amur falcons resting mid-flight from Siberia to Africa — villagers turned from hunting them to guarding them."},
  {"id": "shilloi-lake-nl", "n": "Shilloi Lake", "st": "NL", "t": "lake", "x": 884.4, "y": 445.9, "f": "A foot-shaped lake in Phek’s hills — local tradition holds its waters sacred, so no one fishes it."},
  {"id": "triple-falls-nl", "n": "Triple Falls", "st": "NL", "t": "falls", "x": 847.9, "y": 440.8, "f": "Three clean silver steps in the forest near Seithekema — a staircase of water."},
  {"id": "loktak-lake-mn", "n": "Loktak Lake", "st": "MN", "t": "lake", "x": 849.5, "y": 486.8, "f": "The lake with floating islands — rings of matted reeds called phumdis drift on it, and fishers live on them."},
  {"id": "keibul-lamjao-mn", "n": "Keibul Lamjao", "st": "MN", "t": "park", "x": 850.5, "y": 486.8, "f": "The world’s only floating national park — a giant phumdi where the dancing sangai deer survives."},
  {"id": "shirui-hills-mn", "n": "Shirui Hills", "st": "MN", "t": "peak", "x": 870.1, "y": 465.3, "f": "Home of the Shirui lily — a pale-pink flower found on this one hilltop and nowhere else."},
  {"id": "barak-river-mn", "n": "Barak River", "st": "MN", "t": "river", "x": 833.7, "y": 480.0, "f": "Manipur’s great western river, looping through the hills before watering the Cachar plains."},
  {"id": "sadu-chiru-falls-mn", "n": "Sadu Chiru Falls", "st": "MN", "t": "falls", "x": 846.4, "y": 483.4, "f": "A three-step fall in a green gorge an hour from Imphal — a favourite school-trip wonder."},
  {"id": "koubru-range-mn", "n": "Koubru Range", "st": "MN", "t": "range", "x": 851.1, "y": 473.2, "f": "The sacred northern hills of the Meitei tradition — the valley’s story begins on these slopes, as it is told."},
  {"id": "phawngpui-mz", "n": "Phawngpui", "st": "MZ", "t": "peak", "x": 825.8, "y": 550.6, "f": "The Blue Mountain — Mizoram’s highest peak, wrapped in old tales and, from a distance, truly blue."},
  {"id": "vantawng-falls-mz", "n": "Vantawng Falls", "st": "MZ", "t": "falls", "x": 816.2, "y": 535.6, "f": "Mizoram’s tallest waterfall — a double ribbon dropping through untouched bamboo forest."},
  {"id": "palak-dil-mz", "n": "Palak Dil", "st": "MZ", "t": "lake", "x": 821.0, "y": 565.2, "f": "The largest lake in Mizoram — its name means “swallowing lake”, from an old village-beneath-the-water telling."},
  {"id": "murlen-national-park-mz", "n": "Murlen National Park", "st": "MZ", "t": "park", "x": 833.7, "y": 516.5, "f": "Cloud forest so thick that villagers joke sunlight needs permission to enter."},
  {"id": "dampa-tiger-reserve-mz", "n": "Dampa Tiger Reserve", "st": "MZ", "t": "park", "x": 805.1, "y": 517.5, "f": "Mizoram’s biggest wilderness on the Bangladesh border — clouded leopards pad its ridges."},
  {"id": "tam-dil-mz", "n": "Tam Dil", "st": "MZ", "t": "lake", "x": 822.6, "y": 513.1, "f": "A quiet forest lake whose name means “lake of mustard” — from a telling about a giant mustard plant."},
  {"id": "tlawng-river-mz", "n": "Tlawng River", "st": "MZ", "t": "river", "x": 811.5, "y": 520.9, "f": "Mizoram’s longest river, winding north in loops below Aizawl’s ridge."},
  {"id": "jampui-hills-tr", "n": "Jampui Hills", "st": "TR", "t": "range", "x": 801.0, "y": 505.2, "f": "Tripura’s highest hills — orange orchards, and a sea of clouds below the villages at dawn."},
  {"id": "dumboor-lake-tr", "n": "Dumboor Lake", "st": "TR", "t": "lake", "x": 787.1, "y": 522.6, "f": "A many-armed reservoir dotted with forty-eight islands — its name comes from the drum of Shiva, as it is told."},
  {"id": "sepahijala-sanctuary-tr", "n": "Sepahijala Sanctuary", "st": "TR", "t": "park", "x": 770.6, "y": 515.5, "f": "A lake-and-forest sanctuary famous for the clouded leopard and spectacled langurs."},
  {"id": "gumti-river-tr", "n": "Gumti River", "st": "TR", "t": "river", "x": 776.6, "y": 520.9, "f": "Tripura’s chief river, cutting a gorge through the hills before easing into Bangladesh."},
  {"id": "unakoti-tr", "n": "Unakoti", "st": "TR", "t": "cave", "x": 794.7, "y": 492.9, "f": "A hillside carved with colossal faces of Shiva — “one less than a crore” of images, the telling says, left by a stonemason’s dream."},
  {"id": "trishna-sanctuary-tr", "n": "Trishna Sanctuary", "st": "TR", "t": "park", "x": 776.6, "y": 527.7, "f": "Bison country in Tripura’s south — Indian gaur graze its grassy clearings."},
  {"id": "sohra-cherrapunji-ml", "n": "Sohra (Cherrapunji)", "st": "ML", "t": "range", "x": 783.6, "y": 460.2, "f": "Among the rainiest places on Earth — clouds climb the Khasi cliffs and empty a year of rain in a season."},
  {"id": "mawsynram-ml", "n": "Mawsynram", "st": "ML", "t": "range", "x": 779.2, "y": 459.5, "f": "Holder of the world rainfall record — villagers weave full-body rain shields called knups."},
  {"id": "nohkalikai-falls-ml", "n": "Nohkalikai Falls", "st": "ML", "t": "falls", "x": 782.6, "y": 460.2, "f": "India’s tallest plunge waterfall — a single leap of some 340 metres into a blue-green pool."},
  {"id": "seven-sisters-falls-ml", "n": "Seven Sisters Falls", "st": "ML", "t": "falls", "x": 783.9, "y": 461.2, "f": "Seven parallel ribbons pouring off the Sohra scarp when the monsoon is in — one for each sister state, people like to say."},
  {"id": "living-root-bridges-ml", "n": "Living Root Bridges", "st": "ML", "t": "range", "x": 782.3, "y": 461.2, "f": "Khasi villagers train rubber-fig roots across streams for decades until they become living bridges — stronger every year."},
  {"id": "mawsmai-cave-ml", "n": "Mawsmai Cave", "st": "ML", "t": "cave", "x": 783.9, "y": 461.6, "f": "A walkable limestone cave near Sohra — squeeze the last passage and daylight bursts in green."},
  {"id": "krem-liat-prah-ml", "n": "Krem Liat Prah", "st": "ML", "t": "cave", "x": 806.7, "y": 457.8, "f": "India’s longest known cave — its surveyed passages already run past thirty kilometres, and cavers keep finding more."},
  {"id": "umiam-lake-ml", "n": "Umiam Lake", "st": "ML", "t": "lake", "x": 789.3, "y": 447.3, "f": "The great lake gateway to Shillong — pine shores and kayaks on Khasi hill water."},
  {"id": "balpakram-national-park-ml", "n": "Balpakram National Park", "st": "ML", "t": "park", "x": 756.0, "y": 459.5, "f": "The Garo “land of the spirits” — a plateau canyon where, tradition says, souls rest on their way onward."},
  {"id": "nokrek-national-park-ml", "n": "Nokrek National Park", "st": "ML", "t": "park", "x": 739.2, "y": 454.4, "f": "A biosphere reserve guarding wild citrus — ancestors of the oranges in every basket."},
  {"id": "umngot-at-dawki-ml", "n": "Umngot at Dawki", "st": "ML", "t": "river", "x": 793.1, "y": 462.9, "f": "Water so clear the boats seem to float on air — the riverbed reads like a book beneath you."},
  {"id": "shillong-peak-ml", "n": "Shillong Peak", "st": "ML", "t": "peak", "x": 787.7, "y": 451.0, "f": "The highest point of the Khasi hills — the whole city spreads below like spilled lights at night."},
  {"id": "elephant-falls-ml", "n": "Elephant Falls", "st": "ML", "t": "falls", "x": 786.8, "y": 451.3, "f": "A three-step cascade outside Shillong, renamed by the British for an elephant-shaped rock the 1897 earthquake later broke."},
  {"id": "kaziranga-national-park-as", "n": "Kaziranga National Park", "st": "AS", "t": "park", "x": 829.6, "y": 415.9, "f": "Two-thirds of all the one-horned rhinos on Earth live in this UNESCO grassland — brought back from just a handful a century ago."},
  {"id": "manas-national-park-as", "n": "Manas National Park", "st": "AS", "t": "park", "x": 758.6, "y": 411.1, "f": "A UNESCO park at the Bhutan foothills — golden langurs and pygmy hogs found almost nowhere else."},
  {"id": "brahmaputra-as", "n": "Brahmaputra", "st": "AS", "t": "river", "x": 783.0, "y": 428.8, "f": "India’s only great “male” river — in places it braids ten kilometres wide, an inland sea with a current."},
  {"id": "majuli-as", "n": "Majuli", "st": "AS", "t": "island", "x": 861.3, "y": 403.3, "f": "The world’s largest river island — a whole living culture of satras (monasteries), mask-makers and boat-farmers."},
  {"id": "umananda-as", "n": "Umananda", "st": "AS", "t": "island", "x": 784.2, "y": 428.8, "f": "Possibly the smallest inhabited river island anywhere — one temple hill in the middle of the Brahmaputra."},
  {"id": "dibru-saikhowa-as", "n": "Dibru-Saikhowa", "st": "AS", "t": "park", "x": 900.2, "y": 379.4, "f": "A river-island wilderness where feral horses — descendants of wartime escapees — run wild."},
  {"id": "nameri-national-park-as", "n": "Nameri National Park", "st": "AS", "t": "park", "x": 817.8, "y": 405.0, "f": "A foothill forest crossed by the Jia Bhoroli — home of the rare white-winged wood duck."},
  {"id": "orang-national-park-as", "n": "Orang National Park", "st": "AS", "t": "park", "x": 802.0, "y": 415.2, "f": "A pocket Kaziranga on the north bank — rhinos in a park small enough to know each one."},
  {"id": "barak-assam-as", "n": "Barak (Assam)", "st": "AS", "t": "river", "x": 817.8, "y": 476.6, "f": "The other great river of Assam, watering the Cachar plains far from the Brahmaputra’s valley."},
  {"id": "haflong-hills-as", "n": "Haflong Hills", "st": "AS", "t": "range", "x": 824.8, "y": 464.0, "f": "Assam’s only hill station — blue hills where the plains state finally folds upward."},
  {"id": "chandubi-lake-as", "n": "Chandubi Lake", "st": "AS", "t": "lake", "x": 773.4, "y": 440.1, "f": "A lake born overnight in the great earthquake of 1897 — forest sank, water rose."},
  {"id": "deepor-beel-as", "n": "Deepor Beel", "st": "AS", "t": "wetland", "x": 781.4, "y": 431.2, "f": "Guwahati’s Ramsar wetland — elephants walk down from the hills to feed among the waterbirds."},
  {"id": "son-beel-as", "n": "Son Beel", "st": "AS", "t": "wetland", "x": 805.1, "y": 483.4, "f": "One of Asia’s largest seasonal wetlands — a lake in the rains, a bed of rice and grass in winter."},
  {"id": "chilika-lake-or", "n": "Chilika Lake", "st": "OR", "t": "lake", "x": 580.1, "y": 650.5, "f": "Asia’s largest brackish lagoon — Irrawaddy dolphins inside the bar, and a million winter birds on Nalabana island."},
  {"id": "bhitarkanika-or", "n": "Bhitarkanika", "st": "OR", "t": "park", "x": 630.8, "y": 616.4, "f": "A mangrove maze that shelters giant saltwater crocodiles — some of the largest ever measured."},
  {"id": "simlipal-or", "n": "Simlipal", "st": "OR", "t": "park", "x": 611.8, "y": 580.6, "f": "A tiger biosphere of sal and orchids — and home of the rare black (melanistic) tigers."},
  {"id": "gahirmatha-or", "n": "Gahirmatha", "st": "OR", "t": "coast", "x": 634.0, "y": 616.4, "f": "The world’s largest nesting beach of olive ridley turtles — on a few secret nights, lakhs come ashore together."},
  {"id": "mahanadi-or", "n": "Mahanadi", "st": "OR", "t": "river", "x": 586.4, "y": 626.6, "f": "Odisha’s great river — its delta grew the rice that fed the old kingdoms of Kalinga."},
  {"id": "hirakud-reservoir-or", "n": "Hirakud Reservoir", "st": "OR", "t": "lake", "x": 534.1, "y": 586.7, "f": "Behind one of the longest dams on Earth — a lake so wide villages tell time by its horizon."},
  {"id": "barehipani-falls-or", "n": "Barehipani Falls", "st": "OR", "t": "falls", "x": 614.3, "y": 574.4, "f": "A two-step giant inside Simlipal — among the tallest waterfalls in India."},
  {"id": "duduma-falls-or", "n": "Duduma Falls", "st": "OR", "t": "falls", "x": 494.5, "y": 688.0, "f": "The Machkund river’s roaring plunge on the Andhra border — sacred to the tribes of the hills around it."},
  {"id": "deomali-or", "n": "Deomali", "st": "OR", "t": "peak", "x": 506.5, "y": 686.0, "f": "Odisha’s highest point, in the Eastern Ghats — a bald, windy dome over coffee valleys."},
  {"id": "daringbadi-or", "n": "Daringbadi", "st": "OR", "t": "range", "x": 543.0, "y": 643.7, "f": "The “Kashmir of Odisha” — a hill plateau where winter mornings actually frost."},
  {"id": "satkosia-gorge-or", "n": "Satkosia Gorge", "st": "OR", "t": "river", "x": 564.2, "y": 622.2, "f": "The Mahanadi saws through the Eastern Ghats in a 22 km gorge — gharials bask where the river runs deep."},
  {"id": "ansupa-lake-or", "n": "Ansupa Lake", "st": "OR", "t": "lake", "x": 589.6, "y": 624.2, "f": "A horseshoe freshwater lake off the Mahanadi — lotus beds and winter teal."},
  {"id": "chandipur-or", "n": "Chandipur", "st": "OR", "t": "coast", "x": 634.6, "y": 590.1, "f": "A beach where the sea itself disappears — the tide walks out up to five kilometres and strolls back twice a day."},
  {"id": "chitrakote-falls-ct", "n": "Chitrakote Falls", "st": "CT", "t": "falls", "x": 466.0, "y": 667.5, "f": "The “Niagara of India” — the Indravati drops in a wide horseshoe that turns thunder-brown in the rains."},
  {"id": "tirathgarh-falls-ct", "n": "Tirathgarh Falls", "st": "CT", "t": "falls", "x": 473.3, "y": 676.1, "f": "A stepped cascade in Kanger valley — the water combs out into white curtains."},
  {"id": "kanger-valley-ct", "n": "Kanger Valley", "st": "CT", "t": "park", "x": 473.9, "y": 679.1, "f": "A deep forest valley of caves and streams — one of the last homes of the Bastar hill myna, the state bird that mimics speech."},
  {"id": "kotumsar-cave-ct", "n": "Kotumsar Cave", "st": "CT", "t": "cave", "x": 473.3, "y": 678.8, "f": "An underground limestone world where blind white fish swim — evolved in the dark, they need no eyes."},
  {"id": "indravati-national-park-ct", "n": "Indravati National Park", "st": "CT", "t": "park", "x": 437.4, "y": 667.5, "f": "Chhattisgarh’s tiger reserve — one of the last refuges of the wild buffalo."},
  {"id": "mainpat-ct", "n": "Mainpat", "st": "CT", "t": "range", "x": 516.0, "y": 544.8, "f": "The “Shimla of Chhattisgarh” — a surprise plateau with waterfalls, and a Tibetan settlement making carpets since 1962."},
  {"id": "achanakmar-reserve-ct", "n": "Achanakmar Reserve", "st": "CT", "t": "park", "x": 466.0, "y": 555.0, "f": "Sal forest linking Kanha’s tigers to Chhattisgarh — a green bridge for big cats."},
  {"id": "mahanadi-source-ct", "n": "Mahanadi Source", "st": "CT", "t": "river", "x": 472.3, "y": 636.9, "f": "The great river of Odisha starts here as a stream you can hop across, near Sihawa hill."},
  {"id": "hasdeo-river-ct", "n": "Hasdeo River", "st": "CT", "t": "river", "x": 494.5, "y": 561.8, "f": "The Mahanadi’s forest tributary — its valley holds some of central India’s richest elephant forest."},
  {"id": "barnawapara-ct", "n": "Barnawapara", "st": "CT", "t": "park", "x": 488.1, "y": 592.5, "f": "A compact sanctuary of sal and teak — sloth bears amble its firelines at dusk."},
  {"id": "guru-ghasidas-national-park-ct", "n": "Guru Ghasidas National Park", "st": "CT", "t": "park", "x": 491.3, "y": 517.5, "f": "Chhattisgarh’s newest tiger reserve, named for the saint of the Satnami tradition."},
  {"id": "amrit-dhara-ct", "n": "Amrit Dhara", "st": "CT", "t": "falls", "x": 488.1, "y": 529.4, "f": "A “stream of nectar” falls on the Hasdeo — a Shivratri fair gathers at its foot."},
  {"id": "kanha-national-park-mp", "n": "Kanha National Park", "st": "MP", "t": "park", "x": 432.0, "y": 560.8, "f": "The sal-meadow park that helped inspire the Jungle Book’s world — and saved the swamp deer, barasingha, from the brink."},
  {"id": "bandhavgarh-mp", "n": "Bandhavgarh", "st": "MP", "t": "park", "x": 444.7, "y": 514.1, "f": "An old fort hill ringed by one of the densest tiger populations anywhere — nearly every safari meets stripes."},
  {"id": "pench-national-park-mp", "n": "Pench National Park", "st": "MP", "t": "park", "x": 389.9, "y": 580.6, "f": "The very forest of Kipling’s Mowgli stories — teak country on the Pench river."},
  {"id": "satpura-range-mp", "n": "Satpura Range", "st": "MP", "t": "range", "x": 361.4, "y": 555.0, "f": "The southern of the twin walls across India’s middle — old, forested, full of tigers and tales."},
  {"id": "vindhya-range-mp", "n": "Vindhya Range", "st": "MP", "t": "range", "x": 342.3, "y": 486.8, "f": "The northern wall — in the old geography, where north India ends and the Deccan begins."},
  {"id": "narmada-river-mp", "n": "Narmada River", "st": "MP", "t": "river", "x": 332.8, "y": 555.0, "f": "Flows WEST between the Vindhya and Satpura — one of the few great Indian rivers that refuses the Bay of Bengal."},
  {"id": "marble-rocks-mp", "n": "Marble Rocks", "st": "MP", "t": "river", "x": 405.7, "y": 533.5, "f": "At Bhedaghat the Narmada glides between white marble cliffs — moonlit boat rides feel like floating through sculpture."},
  {"id": "dhuandhar-falls-mp", "n": "Dhuandhar Falls", "st": "MP", "t": "falls", "x": 405.7, "y": 533.2, "f": "“The smoke cascade” — the Narmada crashes so hard the spray hangs like smoke."},
  {"id": "pachmarhi-mp", "n": "Pachmarhi", "st": "MP", "t": "range", "x": 362.3, "y": 556.0, "f": "The “queen of the Satpura” — a British-found plateau of ravines, falls and cave shrines."},
  {"id": "dhupgarh-mp", "n": "Dhupgarh", "st": "MP", "t": "peak", "x": 360.4, "y": 556.7, "f": "The highest point of the Satpura and of MP — sunset watchers climb it like a pilgrimage."},
  {"id": "amarkantak-mp", "n": "Amarkantak", "st": "MP", "t": "spring", "x": 467.5, "y": 549.2, "f": "One hill births two great rivers — the Narmada flows west from here, the Son east."},
  {"id": "chambal-river-mp", "n": "Chambal River", "st": "MP", "t": "river", "x": 332.8, "y": 435.7, "f": "India’s cleanest big river — gharials, river dolphins and skimmers thrive where legend kept people away."},
  {"id": "ken-river-mp", "n": "Ken River", "st": "MP", "t": "river", "x": 412.1, "y": 490.2, "f": "Bundelkhand’s clear river through Panna’s gorges — a gharial sanctuary runs along it."},
  {"id": "betwa-mp-mp", "n": "Betwa (MP)", "st": "MP", "t": "river", "x": 355.0, "y": 503.9, "f": "Granite-bedded and island-strewn — Orchha’s cenotaphs stand on its bank."},
  {"id": "bhimbetka-mp", "n": "Bhimbetka", "st": "MP", "t": "cave", "x": 336.3, "y": 540.0, "f": "Rock shelters painted for over ten thousand years — dancing figures, hunts and animals, a UNESCO gallery of the Stone Age."},
  {"id": "panna-national-park-mp", "n": "Panna National Park", "st": "MP", "t": "park", "x": 412.1, "y": 480.0, "f": "Lost every tiger to poaching by 2009 — then refilled from zero in India’s most famous reintroduction."},
  {"id": "bhojtal-mp", "n": "Bhojtal", "st": "MP", "t": "lake", "x": 328.1, "y": 529.4, "f": "Bhopal’s vast eleventh-century lake, dug by Raja Bhoj — still the city’s drinking water a thousand years on."},
  {"id": "madhav-national-park-mp", "n": "Madhav National Park", "st": "MP", "t": "park", "x": 339.2, "y": 456.1, "f": "Lakes and dry forest by Shivpuri — once royal hunting grounds, now leopard country."},
  {"id": "satpura-tiger-reserve-mp", "n": "Satpura Tiger Reserve", "st": "MP", "t": "park", "x": 355.0, "y": 555.0, "f": "India’s first park to allow walking safaris — you meet the forest on foot, like its first peoples always did."},
  {"id": "thar-desert-rj", "n": "Thar Desert", "st": "RJ", "t": "desert", "x": 142.6, "y": 405.0, "f": "The Great Indian Desert — yet the most crowded desert on Earth, alive with villages, songs and festivals."},
  {"id": "sam-dunes-rj", "n": "Sam Dunes", "st": "RJ", "t": "desert", "x": 110.9, "y": 407.4, "f": "Jaisalmer’s sea of sand — dunes that rebuild themselves with every night’s wind."},
  {"id": "aravalli-range-rj", "n": "Aravalli Range", "st": "RJ", "t": "range", "x": 206.0, "y": 452.7, "f": "Among the oldest mountain ranges on Earth — worn down for over a billion years, and still standing guard against the desert."},
  {"id": "guru-shikhar-rj", "n": "Guru Shikhar", "st": "RJ", "t": "peak", "x": 183.2, "y": 481.7, "f": "The Aravallis’ highest point above Mount Abu — a shrine to Dattatreya crowns it."},
  {"id": "nakki-lake-rj", "n": "Nakki Lake", "st": "RJ", "t": "lake", "x": 181.0, "y": 483.7, "f": "Rajasthan’s only hill-station lake — dug, the telling says, by the gods with their fingernails (nakh)."},
  {"id": "ranthambore-rj", "n": "Ranthambore", "st": "RJ", "t": "park", "x": 301.1, "y": 435.0, "f": "Tigers stalk past a thousand-year fort — the most photographed big cats in the world."},
  {"id": "keoladeo-rj", "n": "Keoladeo", "st": "RJ", "t": "park", "x": 333.5, "y": 396.1, "f": "A hand-made wetland turned UNESCO bird paradise — hundreds of species in a park you explore by cycle."},
  {"id": "desert-national-park-rj", "n": "Desert National Park", "st": "RJ", "t": "park", "x": 114.1, "y": 408.4, "f": "Sand, sewan grass and fossils — the last great home of the critically endangered Great Indian Bustard."},
  {"id": "sariska-rj", "n": "Sariska", "st": "RJ", "t": "park", "x": 297.9, "y": 391.3, "f": "An Aravalli tiger reserve looped around old temples — tigers were returned here after vanishing in 2004."},
  {"id": "sambhar-lake-rj", "n": "Sambhar Lake", "st": "RJ", "t": "lake", "x": 256.1, "y": 404.6, "f": "India’s largest inland salt lake — pink with flamingos in season, white with salt pans always."},
  {"id": "pushkar-lake-rj", "n": "Pushkar Lake", "st": "RJ", "t": "lake", "x": 239.3, "y": 419.0, "f": "The sacred lake of fifty-two ghats — half a million camels and pilgrims arrive together at the Kartik fair."},
  {"id": "lake-pichola-rj", "n": "Lake Pichola", "st": "RJ", "t": "lake", "x": 211.7, "y": 484.4, "f": "Udaipur’s six-century lake — palaces float on it like anchored ships."},
  {"id": "chambal-rajasthan-rj", "n": "Chambal (Rajasthan)", "st": "RJ", "t": "river", "x": 294.8, "y": 456.1, "f": "The ravine river out of the Vindhyas — its Rajasthan gorges shelter gharial and skimmer."},
  {"id": "luni-river-rj", "n": "Luni River", "st": "RJ", "t": "river", "x": 164.8, "y": 442.5, "f": "The desert’s own river — it rises near Ajmer, turns salty on its way, and ends in the Rann without meeting any sea."},
  {"id": "indira-gandhi-canal-rj", "n": "Indira Gandhi Canal", "st": "RJ", "t": "river", "x": 206.0, "y": 350.4, "f": "A river people built — Himalayan water carried six hundred kilometres into the Thar, turning dunes to fields."},
  {"id": "menar-wetland-rj", "n": "Menar Wetland", "st": "RJ", "t": "wetland", "x": 225.0, "y": 485.1, "f": "The “bird village” — two lakes whose farmers have guarded waterbirds for generations as a point of pride."},
  {"id": "great-rann-of-kutch-gj", "n": "Great Rann of Kutch", "st": "GJ", "t": "desert", "x": 107.8, "y": 507.3, "f": "A salt desert that floods into a shallow sea each monsoon and dries into blinding white — moonlit, it glows."},
  {"id": "little-rann-gj", "n": "Little Rann", "st": "GJ", "t": "desert", "x": 133.1, "y": 527.7, "f": "Salt flats and grass islands — the last wild home of the khur, the Indian wild ass."},
  {"id": "gir-national-park-gj", "n": "Gir National Park", "st": "GJ", "t": "park", "x": 120.4, "y": 602.1, "f": "The only place on Earth where wild lions live outside Africa — saved by the Nawab of Junagadh’s ban a century ago."},
  {"id": "girnar-gj", "n": "Girnar", "st": "GJ", "t": "peak", "x": 110.9, "y": 589.1, "f": "Gujarat’s highest mountain — ten thousand steps thread its Jain and Hindu shrines."},
  {"id": "marine-national-park-gj", "n": "Marine National Park", "st": "GJ", "t": "coast", "x": 82.4, "y": 556.0, "f": "India’s first marine park, in the Gulf of Kutch — at low tide you walk among corals, octopus and sea anemones."},
  {"id": "velavadar-gj", "n": "Velavadar", "st": "GJ", "t": "park", "x": 158.5, "y": 571.0, "f": "Golden grassland where blackbuck herds run like water — and harriers gather in one of the world’s largest roosts."},
  {"id": "nal-sarovar-gj", "n": "Nal Sarovar", "st": "GJ", "t": "wetland", "x": 160.1, "y": 545.1, "f": "Gujarat’s great bird lake — flat-bottomed boats drift among cranes, pelicans and flamingos."},
  {"id": "narmada-estuary-gj", "n": "Narmada Estuary", "st": "GJ", "t": "river", "x": 187.0, "y": 582.3, "f": "The west-flowing giant meets the sea at Bharuch — one of India’s oldest port coasts."},
  {"id": "sabarmati-gj", "n": "Sabarmati", "st": "GJ", "t": "river", "x": 176.9, "y": 538.0, "f": "Ahmedabad’s river — Gandhi set his ashram on its bank, and the city now strolls its riverfront."},
  {"id": "tapi-river-gj", "n": "Tapi River", "st": "GJ", "t": "river", "x": 187.0, "y": 599.3, "f": "The other west-flowing river of the peninsula — Surat grew rich at its mouth."},
  {"id": "saputara-gj", "n": "Saputara", "st": "GJ", "t": "range", "x": 213.9, "y": 620.5, "f": "Gujarat’s one hill station, in the Sahyadri’s northern folds — the “abode of serpents”, honoured at its river."},
  {"id": "thol-wetland-gj", "n": "Thol Wetland", "st": "GJ", "t": "wetland", "x": 171.2, "y": 533.5, "f": "A shallow reservoir turned Ramsar refuge — cranes fly in at dusk in long ribbons."},
  {"id": "khijadiya-gj", "n": "Khijadiya", "st": "GJ", "t": "wetland", "x": 98.2, "y": 555.0, "f": "Freshwater on one side of an old bund, saltwater on the other — two wetlands in one, doubling the birds."},
  {"id": "ninai-falls-gj", "n": "Ninai Falls", "st": "GJ", "t": "falls", "x": 209.2, "y": 582.3, "f": "A monsoon horsetail in the Dang forests — the Narmada country’s green surprise."},
  {"id": "western-ghats-sahyadri-mh", "n": "Western Ghats (Sahyadri)", "st": "MH", "t": "range", "x": 206.0, "y": 691.4, "f": "A UNESCO mountain wall older than the Himalaya — its rain shadow writes the weather of half the peninsula."},
  {"id": "kalsubai-mh", "n": "Kalsubai", "st": "MH", "t": "peak", "x": 212.7, "y": 653.9, "f": "Maharashtra’s highest point — ladders bolted to the rock take pilgrims to the little shrine on top."},
  {"id": "tadoba-mh", "n": "Tadoba", "st": "MH", "t": "park", "x": 393.0, "y": 631.7, "f": "Maharashtra’s oldest and largest tiger reserve — bamboo forest where sightings feel almost promised."},
  {"id": "melghat-mh", "n": "Melghat", "st": "MH", "t": "park", "x": 323.3, "y": 592.5, "f": "One of the first Project Tiger reserves (1973) — rugged Satpura country of teak and cliffs."},
  {"id": "sanjay-gandhi-national-park-mh", "n": "Sanjay Gandhi National Park", "st": "MH", "t": "park", "x": 187.0, "y": 666.9, "f": "A whole national park inside a megacity — leopards live wild within sight of Mumbai’s towers, beside the ancient Kanheri caves."},
  {"id": "bhimashankar-mh", "n": "Bhimashankar", "st": "MH", "t": "park", "x": 207.6, "y": 672.0, "f": "Misty crestline sanctuary of the Indian giant squirrel — the shekru, Maharashtra’s own state animal."},
  {"id": "lonar-lake-mh", "n": "Lonar Lake", "st": "MH", "t": "lake", "x": 301.4, "y": 640.9, "f": "A lake in a meteor crater — some fifty thousand years ago a space rock struck basalt here; the water is both salty and alkaline."},
  {"id": "godavari-source-mh", "n": "Godavari Source", "st": "MH", "t": "river", "x": 207.0, "y": 642.3, "f": "The Dakshin Ganga — south India’s longest river — starts at Trimbakeshwar on Brahmagiri hill."},
  {"id": "krishna-source-mh", "n": "Krishna Source", "st": "MH", "t": "river", "x": 211.1, "y": 711.2, "f": "The Krishna rises at Mahabaleshwar — five rivers begin on this one wet plateau."},
  {"id": "thoseghar-falls-mh", "n": "Thoseghar Falls", "st": "MH", "t": "falls", "x": 217.1, "y": 722.1, "f": "Monsoon cascades pouring off the Konkan edge near Satara — a whole valley of falling water."},
  {"id": "matheran-mh", "n": "Matheran", "st": "MH", "t": "range", "x": 198.7, "y": 675.0, "f": "Asia’s only no-car hill station — you arrive by toy train or on foot, and the forest stays quiet."},
  {"id": "mahabaleshwar-mh", "n": "Mahabaleshwar", "st": "MH", "t": "range", "x": 211.1, "y": 711.2, "f": "The strawberry plateau of the Sahyadri — cliff “points” look down kilometres of green."},
  {"id": "chikhaldara-mh", "n": "Chikhaldara", "st": "MH", "t": "range", "x": 327.4, "y": 592.5, "f": "Vidarbha’s only hill station — coffee grows here, far from the south’s plantations."},
  {"id": "konkan-coast-mh", "n": "Konkan Coast", "st": "MH", "t": "coast", "x": 199.7, "y": 742.6, "f": "A laterite coast of coves, creeks and fishing villages — Alphonso mango country."},
  {"id": "elephanta-island-mh", "n": "Elephanta Island", "st": "MH", "t": "island", "x": 188.0, "y": 675.7, "f": "A forested harbour island whose rock-cut cave shrine holds the great three-faced Shiva — a UNESCO site an hour’s boat from the Gateway."},
  {"id": "dudhsagar-falls-ga", "n": "Dudhsagar Falls", "st": "GA", "t": "falls", "x": 231.7, "y": 800.2, "f": "The “sea of milk” — a 300 m tiered giant on the Mandovi; the railway crosses right through its spray."},
  {"id": "mandovi-river-ga", "n": "Mandovi River", "st": "GA", "t": "river", "x": 218.7, "y": 793.7, "f": "Goa’s lifeline river — ferries, floating casinos and old Portuguese quays on one short, busy stream."},
  {"id": "mollem-national-park-ga", "n": "Mollem National Park", "st": "GA", "t": "park", "x": 228.2, "y": 797.1, "f": "The Western Ghats’ Goan gate — gaur, kingfishers, and the Devil’s Canyon gorge."},
  {"id": "salim-ali-bird-sanctuary-ga", "n": "Salim Ali Bird Sanctuary", "st": "GA", "t": "wetland", "x": 217.4, "y": 793.7, "f": "A mangrove island in the Mandovi named for India’s birdman — herons at arm’s length from the boat."},
  {"id": "calangute-ga", "n": "Calangute", "st": "GA", "t": "coast", "x": 213.9, "y": 792.3, "f": "The queen of Goa’s beaches — a long golden curve that made the state famous."},
  {"id": "chorao-island-ga", "n": "Chorao Island", "st": "GA", "t": "island", "x": 219.7, "y": 793.4, "f": "A river island of paddy bunds and mangrove — village Goa an oar’s pull from the capital."},
  {"id": "chandranath-hill-ga", "n": "Chandranath Hill", "st": "GA", "t": "range", "x": 221.2, "y": 803.9, "f": "A lone forested hill over Salcete — its old moon-linked shrine watches the paddy plains."},
  {"id": "jog-falls-ka", "n": "Jog Falls", "st": "KA", "t": "falls", "x": 247.5, "y": 837.0, "f": "The Sharavathi leaps 250 m in four ropes of water — among the tallest plunge falls in India, deafening in the rains."},
  {"id": "mullayanagiri-ka", "n": "Mullayanagiri", "st": "KA", "t": "peak", "x": 276.4, "y": 865.7, "f": "Karnataka’s highest peak, above the coffee bowls of Chikkamagaluru."},
  {"id": "kudremukh-ka", "n": "Kudremukh", "st": "KA", "t": "peak", "x": 261.5, "y": 864.6, "f": "The “horse-face” peak — grass hills rolling to the sea-haze, over one of India’s wettest forests."},
  {"id": "kodagu-coorg-ka", "n": "Kodagu (Coorg)", "st": "KA", "t": "range", "x": 277.0, "y": 898.7, "f": "Coffee country of the Kodava people — India’s coffee story largely grew up on these slopes."},
  {"id": "nagarhole-ka", "n": "Nagarhole", "st": "KA", "t": "park", "x": 289.4, "y": 911.7, "f": "Kabini-side forest famous for huge elephant gatherings — and, some seasons, a black panther."},
  {"id": "bandipur-ka", "n": "Bandipur", "st": "KA", "t": "park", "x": 305.2, "y": 924.3, "f": "A founding Project Tiger reserve on the old Mysore hunting grounds — dry teak forest full of life."},
  {"id": "kabini-reservoir-ka", "n": "Kabini Reservoir", "st": "KA", "t": "lake", "x": 296.4, "y": 914.1, "f": "In summer, Asia’s largest gathering of wild elephants assembles on its drawdown banks."},
  {"id": "kaveri-river-ka", "n": "Kaveri River", "st": "KA", "t": "river", "x": 307.5, "y": 899.4, "f": "The great river of the south’s rice and music — temples, islands and arguments have followed her for two thousand years."},
  {"id": "shivanasamudra-ka", "n": "Shivanasamudra", "st": "KA", "t": "falls", "x": 322.4, "y": 902.8, "f": "Twin falls on the Kaveri — Asia’s first big hydroelectric station lit up here in 1902."},
  {"id": "talakaveri-ka", "n": "Talakaveri", "st": "KA", "t": "spring", "x": 269.1, "y": 900.1, "f": "The Kaveri’s source — a small spring-fed tank on a Kodagu hillside where the river is born, honoured with a festival."},
  {"id": "tungabhadra-ka", "n": "Tungabhadra", "st": "KA", "t": "river", "x": 294.8, "y": 800.5, "f": "The river of Hampi — it slides through granite boulders past the old capital’s ruins."},
  {"id": "agumbe-ka", "n": "Agumbe", "st": "KA", "t": "range", "x": 256.4, "y": 861.9, "f": "The “Cherrapunji of the south” — rainforest research country and the king cobra’s capital."},
  {"id": "st-mary-u2019s-islands-ka", "n": "St Mary\\u2019s Islands", "st": "KA", "t": "island", "x": 243.1, "y": 866.0, "f": "Islands of hexagonal basalt columns — rock that crystallised when Madagascar tore away from India."},
  {"id": "ranganathittu-ka", "n": "Ranganathittu", "st": "KA", "t": "wetland", "x": 305.9, "y": 898.7, "f": "Islets in the Kaveri where storks and pelicans nest in trees above basking crocodiles — a boat glides you past."},
  {"id": "gokarna-ka", "n": "Gokarna", "st": "KA", "t": "coast", "x": 232.0, "y": 826.1, "f": "Om-shaped beach coves below a temple town — the coast at its calmest."},
  {"id": "dandeli-ka", "n": "Dandeli", "st": "KA", "t": "park", "x": 241.5, "y": 801.6, "f": "Hornbill forests on the black-water Kali — Karnataka’s white-water rafting river."},
  {"id": "abbey-falls-ka", "n": "Abbey Falls", "st": "KA", "t": "falls", "x": 276.4, "y": 897.4, "f": "Coorg’s coffee-estate waterfall — spice vines to one side, monsoon thunder on the other."},
  {"id": "anamudi-kl", "n": "Anamudi", "st": "KL", "t": "peak", "x": 318.9, "y": 975.5, "f": "The highest peak in India south of the Himalaya (2,695 m) — “elephant’s forehead”, and it looks it."},
  {"id": "eravikulam-kl", "n": "Eravikulam", "st": "KL", "t": "park", "x": 318.6, "y": 974.4, "f": "High grass hills of the Nilgiri tahr — and of the neelakurinji, the blue flower that blooms once in twelve years and turns the slopes violet."},
  {"id": "periyar-kl", "n": "Periyar", "st": "KL", "t": "park", "x": 324.6, "y": 999.7, "f": "A tiger reserve around a century-old lake — you watch elephants from a drifting boat."},
  {"id": "munnar-kl", "n": "Munnar", "st": "KL", "t": "range", "x": 318.9, "y": 978.2, "f": "Tea to every horizon — a green staircase world a mile above the sea."},
  {"id": "vembanad-lake-kl", "n": "Vembanad Lake", "st": "KL", "t": "lake", "x": 298.6, "y": 994.9, "f": "India’s longest lake — the heart of the backwaters, where houseboats drift past paddy and church spires, and snake boats race at Onam."},
  {"id": "ashtamudi-kl", "n": "Ashtamudi", "st": "KL", "t": "lake", "x": 302.7, "y": 1017.1, "f": "The eight-armed lake of Kollam — a Ramsar octopus of calm water."},
  {"id": "athirappilly-kl", "n": "Athirappilly", "st": "KL", "t": "falls", "x": 303.3, "y": 971.4, "f": "Kerala’s biggest waterfall — a wide white wall on the Chalakudy, star of a hundred films."},
  {"id": "silent-valley-kl", "n": "Silent Valley", "st": "KL", "t": "park", "x": 299.5, "y": 944.4, "f": "A rainforest so old and untouched it became the emblem of India’s green movement — saved from a dam by public love in the 1980s."},
  {"id": "wayanad-kl", "n": "Wayanad", "st": "KL", "t": "range", "x": 288.4, "y": 923.3, "f": "Spice-garden plateau of coffee, pepper and paddy — with prehistoric carvings in its Edakkal cave."},
  {"id": "edakkal-caves-kl", "n": "Edakkal Caves", "st": "KL", "t": "cave", "x": 292.6, "y": 926.0, "f": "A cleft in the rock carved with figures thousands of years old — a message board of the Stone Age."},
  {"id": "periyar-river-kl", "n": "Periyar River", "st": "KL", "t": "river", "x": 297.9, "y": 977.9, "f": "Kerala’s longest river — from the high ranges to the backwaters, it powers and waters the state."},
  {"id": "bharathappuzha-kl", "n": "Bharathappuzha", "st": "KL", "t": "river", "x": 291.6, "y": 954.0, "f": "The “river of Bharata” — Kerala’s second river, cradle of its arts and festivals along sandy banks."},
  {"id": "kuttanad-kl", "n": "Kuttanad", "st": "KL", "t": "wetland", "x": 297.9, "y": 1001.7, "f": "The rice bowl BELOW sea level — farmers here grow paddy behind bunds, under the waterline, like a green Netherlands."},
  {"id": "varkala-cliffs-kl", "n": "Varkala Cliffs", "st": "KL", "t": "coast", "x": 307.5, "y": 1024.6, "f": "Red laterite cliffs dropping straight to the beach — rare on India’s flat western shore."},
  {"id": "kovalam-kl", "n": "Kovalam", "st": "KL", "t": "coast", "x": 317.0, "y": 1035.8, "f": "The lighthouse beach that introduced Kerala to the world — three coves under a striped tower."},
  {"id": "ponmudi-kl", "n": "Ponmudi", "st": "KL", "t": "range", "x": 320.8, "y": 1023.5, "f": "The “golden peak” above Thiruvananthapuram — twenty-two hairpins up into cloud tea-gardens."},
  {"id": "nilgiris-tn", "n": "Nilgiris", "st": "TN", "t": "range", "x": 307.5, "y": 933.5, "f": "The Blue Mountains — named for the kurinji haze; the toy train has climbed them since 1908."},
  {"id": "doddabetta-tn", "n": "Doddabetta", "st": "TN", "t": "peak", "x": 308.7, "y": 933.5, "f": "The Nilgiris’ highest point above Ooty — on clear days the plains swim far below."},
  {"id": "mudumalai-tn", "n": "Mudumalai", "st": "TN", "t": "park", "x": 302.1, "y": 927.7, "f": "Tiger reserve at the Ghats’ meeting point — elephants amble the Mysore road at dusk."},
  {"id": "anamalai-tiger-reserve-tn", "n": "Anamalai Tiger Reserve", "st": "TN", "t": "park", "x": 317.0, "y": 969.3, "f": "The “elephant hills” park — rainforest sholas above, lion-tailed macaques within."},
  {"id": "palani-hills-tn", "n": "Palani Hills", "st": "TN", "t": "range", "x": 332.8, "y": 974.4, "f": "Kodaikanal’s range — star-shaped lake, pear orchards and cliff walks in the mist."},
  {"id": "kodaikanal-lake-tn", "n": "Kodaikanal Lake", "st": "TN", "t": "lake", "x": 332.5, "y": 973.4, "f": "A star-shaped hill lake made in 1863 — cycle its five quiet kilometres round."},
  {"id": "kaveri-delta-tn", "n": "Kaveri Delta", "st": "TN", "t": "river", "x": 396.2, "y": 954.0, "f": "The rice bowl of the south — the river fans into a thousand channels the Cholas first engineered."},
  {"id": "hogenakkal-tn", "n": "Hogenakkal", "st": "TN", "t": "falls", "x": 341.4, "y": 909.0, "f": "“Smoking rocks” — the Kaveri splits into a dozen falls, and coracle boats spin right up to the spray."},
  {"id": "courtallam-tn", "n": "Courtallam", "st": "TN", "t": "falls", "x": 325.8, "y": 1017.7, "f": "The “spa of the south” — nine falls whose herb-washed water people bathe in for health, as generations have."},
  {"id": "pichavaram-tn", "n": "Pichavaram", "st": "TN", "t": "wetland", "x": 405.4, "y": 932.5, "f": "A mangrove labyrinth explored by rowboat — green tunnels of breathing roots."},
  {"id": "point-calimere-tn", "n": "Point Calimere", "st": "TN", "t": "coast", "x": 407.6, "y": 971.0, "f": "A wild sandy cape of blackbuck and flamingos where the Coromandel turns."},
  {"id": "gulf-of-mannar-tn", "n": "Gulf of Mannar", "st": "TN", "t": "coast", "x": 380.4, "y": 1012.0, "f": "India’s first marine biosphere — 21 coral islets, sea-cows grazing seagrass meadows."},
  {"id": "pamban-island-tn", "n": "Pamban Island", "st": "TN", "t": "island", "x": 389.9, "y": 1005.8, "f": "Rameswaram’s island, reached by the century-old sea bridge — trains cross with the waves beneath."},
  {"id": "dhanushkodi-tn", "n": "Dhanushkodi", "st": "TN", "t": "coast", "x": 394.3, "y": 1010.2, "f": "A sand spit where the Bay of Bengal and the Indian Ocean visibly meet — the tellings place Rama’s bridge from this shore."},
  {"id": "marina-beach-tn", "n": "Marina Beach", "st": "TN", "t": "coast", "x": 420.9, "y": 877.3, "f": "One of the longest urban beaches on Earth — Chennai’s whole world walks here at dusk."},
  {"id": "vaigai-river-tn", "n": "Vaigai River", "st": "TN", "t": "river", "x": 351.8, "y": 984.7, "f": "Madurai’s river — the sangam poems and temple festivals have kept its name for two millennia."},
  {"id": "yercaud-tn", "n": "Yercaud", "st": "TN", "t": "range", "x": 355.0, "y": 920.6, "f": "The Shevaroy hills’ coffee-and-orange station — the “poor man’s Ooty”, said with love."},
  {"id": "meghamalai-tn", "n": "Meghamalai", "st": "TN", "t": "range", "x": 329.6, "y": 993.2, "f": "The “high wavy mountains” — cloud-brushed tea ridges above Theni."},
  {"id": "godavari-delta-ap", "n": "Godavari Delta", "st": "AP", "t": "river", "x": 469.1, "y": 752.8, "f": "The south’s largest river opens into a green fan at Rajahmundry — coconut lanes and canal boats."},
  {"id": "krishna-ap-ap", "n": "Krishna (AP)", "st": "AP", "t": "river", "x": 431.1, "y": 759.6, "f": "The peninsula’s second great river — at Vijayawada it squeezes between hills under Prakasam’s gates."},
  {"id": "papikonda-ap", "n": "Papikonda", "st": "AP", "t": "park", "x": 456.4, "y": 728.9, "f": "Hills that pinch the Godavari into a fjord-like gorge — best seen from the Bhadrachalam launch."},
  {"id": "borra-caves-ap", "n": "Borra Caves", "st": "AP", "t": "cave", "x": 508.4, "y": 698.9, "f": "Million-year limestone halls in the Ananthagiri hills — a shrine sits deep inside among the stalagmites."},
  {"id": "araku-valley-ap", "n": "Araku Valley", "st": "AP", "t": "range", "x": 503.0, "y": 697.2, "f": "A tribal coffee valley reached by one of India’s prettiest railways — sixty tunnels through the Ghats."},
  {"id": "lambasingi-ap", "n": "Lambasingi", "st": "AP", "t": "range", "x": 492.3, "y": 712.9, "f": "The “Kashmir of Andhra” — the one south-coast village where winter can touch frost."},
  {"id": "kolleru-lake-ap", "n": "Kolleru Lake", "st": "AP", "t": "lake", "x": 450.1, "y": 754.5, "f": "A giant shallow lake between the two deltas — grey pelicans nest here in colonies."},
  {"id": "pulicat-lake-ap", "n": "Pulicat Lake", "st": "AP", "t": "lake", "x": 421.6, "y": 856.5, "f": "India’s second-largest lagoon — flamingos wade its shallows beside the rocket coast."},
  {"id": "sri-venkateswara-np-ap", "n": "Sri Venkateswara NP", "st": "AP", "t": "park", "x": 391.5, "y": 850.7, "f": "Seshachalam’s red-sanders forests around Tirumala — gorges hide the tall Talakona fall."},
  {"id": "talakona-falls-ap", "n": "Talakona Falls", "st": "AP", "t": "falls", "x": 387.3, "y": 851.0, "f": "Andhra’s tallest waterfall, deep in the Seshachalam forest — its water is held locally to heal."},
  {"id": "ethipothala-ap", "n": "Ethipothala", "st": "AP", "t": "falls", "x": 393.0, "y": 757.9, "f": "A three-stream fall near Nagarjuna Sagar, lit up at dusk — crocodiles are bred in its pool below."},
  {"id": "horsley-hills-ap", "n": "Horsley Hills", "st": "AP", "t": "range", "x": 361.4, "y": 856.5, "f": "A cool granite knuckle above the Rayalaseema plains — eucalyptus and huge old banyans."},
  {"id": "nagarjuna-sagar-ap", "n": "Nagarjuna Sagar", "st": "AP", "t": "lake", "x": 390.2, "y": 757.2, "f": "One of the world’s great masonry dams floods a Buddhist valley — the excavated stupas were moved stone-by-stone to an island museum."},
  {"id": "coringa-ap", "n": "Coringa", "st": "AP", "t": "wetland", "x": 485.6, "y": 749.4, "f": "India’s second-largest mangrove stand, guarding the Godavari mouth — a nursery for the whole coast’s fish."},
  {"id": "gandikota-gorge-ap", "n": "Gandikota Gorge", "st": "AP", "t": "river", "x": 357.9, "y": 816.9, "f": "The “Grand Canyon of India” — the Penna slices a red sandstone chasm below a medieval fort."},
  {"id": "godavari-at-bhadrachalam-tg", "n": "Godavari at Bhadrachalam", "st": "TG", "t": "river", "x": 440.0, "y": 719.7, "f": "The great river runs broad and slow past the temple town — coracles cross as they always have."},
  {"id": "krishna-telangana-tg", "n": "Krishna (Telangana)", "st": "TG", "t": "river", "x": 374.0, "y": 763.0, "f": "Forms the state’s southern rim through deep gneiss gorges — leopard and croc country."},
  {"id": "kawal-tiger-reserve-tg", "n": "Kawal Tiger Reserve", "st": "TG", "t": "park", "x": 377.2, "y": 671.0, "f": "Teak and bamboo on the Godavari’s north bank — a corridor for tigers walking in from Maharashtra."},
  {"id": "amrabad-tiger-reserve-tg", "n": "Amrabad Tiger Reserve", "st": "TG", "t": "park", "x": 377.2, "y": 763.0, "f": "One of India’s largest tiger reserves — the Chenchu forest people live within it as its oldest guardians."},
  {"id": "hussain-sagar-tg", "n": "Hussain Sagar", "st": "TG", "t": "lake", "x": 363.6, "y": 728.2, "f": "A 16th-century lake joining Hyderabad and Secunderabad — a giant stone Buddha stands mid-water."},
  {"id": "pakhal-lake-tg", "n": "Pakhal Lake", "st": "TG", "t": "lake", "x": 411.4, "y": 710.2, "f": "A Kakatiya-era tank from the 13th century — the old engineers’ lakes still water Telangana."},
  {"id": "kuntala-falls-tg", "n": "Kuntala Falls", "st": "TG", "t": "falls", "x": 363.3, "y": 662.4, "f": "Telangana’s tallest waterfall on the Kadem river — named, the telling goes, for Shakuntala who bathed here."},
  {"id": "bogatha-falls-tg", "n": "Bogatha Falls", "st": "TG", "t": "falls", "x": 432.7, "y": 711.9, "f": "The “Niagara of Telangana” — a wide curtain in the Godavari forests."},
  {"id": "ananthagiri-hills-tg", "n": "Ananthagiri Hills", "st": "TG", "t": "range", "x": 345.5, "y": 731.0, "f": "Forest hills where the Musi river rises — Hyderabad’s weekend woods."},
  {"id": "deccan-plateau-tg", "n": "Deccan Plateau", "st": "TG", "t": "range", "x": 380.4, "y": 715.3, "f": "Telangana rides the great volcanic tableland — black soils, boulder hills and tank-fed fields."},
  {"id": "pocharam-lake-tg", "n": "Pocharam Lake", "st": "TG", "t": "wetland", "x": 355.0, "y": 704.4, "f": "A century-old reservoir sanctuary — winter home to pelicans and painted storks."},
  {"id": "yamuna-at-delhi-dl", "n": "Yamuna at Delhi", "st": "DL", "t": "river", "x": 324.9, "y": 343.6, "f": "The capital grew on this floodplain — every one of Delhi’s seven-plus cities kept close to her bank."},
  {"id": "delhi-ridge-dl", "n": "Delhi Ridge", "st": "DL", "t": "range", "x": 322.4, "y": 347.0, "f": "The Aravallis’ last northern outcrop — a billion-year-old rock spine that is the city’s green lung."},
  {"id": "asola-bhatti-sanctuary-dl", "n": "Asola Bhatti Sanctuary", "st": "DL", "t": "park", "x": 323.3, "y": 353.8, "f": "Old mining badlands healed into thorn forest — nilgai and hyena minutes from the metro."},
  {"id": "najafgarh-jheel-dl", "n": "Najafgarh Jheel", "st": "DL", "t": "wetland", "x": 316.3, "y": 350.4, "f": "A once-vast lake returning as a wetland — winter birds are reclaiming the capital’s southwest."},
  {"id": "hauz-khas-dl", "n": "Hauz Khas", "st": "DL", "t": "lake", "x": 323.0, "y": 348.7, "f": "A 13th-century royal tank that still holds water — madrasa domes look down on ducks."},
  {"id": "sukhna-lake-ch", "n": "Sukhna Lake", "st": "CH", "t": "lake", "x": 311.3, "y": 274.0, "f": "The planned city’s hand-made lake under the Shivaliks — rowing at dawn, migratory ducks in winter."},
  {"id": "sukhna-sanctuary-ch", "n": "Sukhna Sanctuary", "st": "CH", "t": "park", "x": 311.9, "y": 273.3, "f": "The lake’s guardian forest — planted to hold the hills’ silt, now full of sambar."},
  {"id": "shivalik-edge-ch", "n": "Shivalik Edge", "st": "CH", "t": "range", "x": 312.5, "y": 272.7, "f": "The city was drawn right at the hills’ feet — Corbusier set his Capitol against this backdrop."},
  {"id": "promenade-beach-py", "n": "Promenade Beach", "st": "PY", "t": "coast", "x": 406.7, "y": 915.4, "f": "The old French seafront — the sea wall walk that gives the town its evening life."},
  {"id": "ousteri-lake-py", "n": "Ousteri Lake", "st": "PY", "t": "lake", "x": 403.8, "y": 914.8, "f": "The territory’s largest lake — a Ramsar wetland of pelicans and lilies."},
  {"id": "chunnambar-py", "n": "Chunnambar", "st": "PY", "t": "wetland", "x": 405.7, "y": 917.2, "f": "A backwater where the river meets the sea — boats cross to a sandbar beach."},
  {"id": "saddle-peak-an", "n": "Saddle Peak", "st": "AN", "t": "peak", "x": 824.8, "y": 873.2, "f": "The islands’ highest point — rainforest all the way up, reef-blue sea all the way down."},
  {"id": "barren-island-an", "n": "Barren Island", "st": "AN", "t": "island", "x": 851.4, "y": 903.5, "f": "India’s only active volcano — it still puffs and glows over the empty sea."},
  {"id": "radhanagar-beach-an", "n": "Radhanagar Beach", "st": "AN", "t": "coast", "x": 822.6, "y": 913.7, "f": "A perfect white curve on Havelock — often counted among Asia’s best beaches."},
  {"id": "mahatma-gandhi-marine-np-an", "n": "Mahatma Gandhi Marine NP", "st": "AN", "t": "coast", "x": 811.8, "y": 927.7, "f": "Reef gardens off Wandoor — glass-bottom boats over coral cities."},
  {"id": "baratang-limestone-caves-an", "n": "Baratang Limestone Caves", "st": "AN", "t": "cave", "x": 817.2, "y": 909.6, "f": "Sea-carved limestone halls reached by mangrove creek — with a mud volcano bubbling nearby."},
  {"id": "campbell-bay-np-an", "n": "Campbell Bay NP", "st": "AN", "t": "park", "x": 852.7, "y": 1083.6, "f": "Great Nicobar’s biosphere — crab-eating macaques and megapode birds that build compost-heap nests."},
  {"id": "indira-point-an", "n": "Indira Point", "st": "AN", "t": "coast", "x": 850.8, "y": 1092.1, "f": "India’s southernmost tip — a lighthouse closer to Sumatra than to the mainland."},
  {"id": "ross-smith-an", "n": "Ross & Smith", "st": "AN", "t": "island", "x": 826.7, "y": 868.7, "f": "Twin islands joined by a walkable sandbar — cross the sea on foot at low tide."},
  {"id": "coral-atolls-ld", "n": "Coral Atolls", "st": "LD", "t": "island", "x": 177.5, "y": 960.8, "f": "India’s only coral-atoll territory — rings of reef around turquoise lagoons."},
  {"id": "bangaram-lagoon-ld", "n": "Bangaram Lagoon", "st": "LD", "t": "coast", "x": 167.3, "y": 949.2, "f": "An uninhabited atoll’s glowing lagoon — plankton light the night water blue."},
  {"id": "minicoy-ld", "n": "Minicoy", "st": "LD", "t": "island", "x": 191.8, "y": 1039.9, "f": "The southern outlier with its 1885 lighthouse — closer in language and boats to the Maldives’ world."},
  {"id": "pitti-bird-sanctuary-ld", "n": "Pitti Bird Sanctuary", "st": "LD", "t": "wetland", "x": 177.5, "y": 953.0, "f": "A bare sand islet where terns nest by the thousand — protected as their nursery."},
  {"id": "kavaratti-lagoon-ld", "n": "Kavaratti Lagoon", "st": "LD", "t": "coast", "x": 178.8, "y": 962.2, "f": "The capital’s home lagoon — glass-boat gardens of coral and clams."},
  {"id": "daman-ganga-dd", "n": "Daman Ganga", "st": "DD", "t": "river", "x": 187.0, "y": 626.6, "f": "The little river that reaches the sea between two old Portuguese towns."},
  {"id": "satmaliya-sanctuary-dn", "n": "Satmaliya Sanctuary", "st": "DN", "t": "park", "x": 190.8, "y": 633.4, "f": "Silvassa’s deer park forest — chital and sambar in teak country."},
  {"id": "naida-caves-dd", "n": "Naida Caves", "st": "DD", "t": "cave", "x": 124.2, "y": 615.7, "f": "Quarry-carved chambers on Diu — sunlight shafts through square skylights in the rock."},
  {"id": "jampore-beach-dd", "n": "Jampore Beach", "st": "DD", "t": "coast", "x": 184.5, "y": 627.6, "f": "Daman’s calm casuarina beach — shallow tides that walk far out."},
  ]
};
