/* Bizzing India — geography data for the Living Map.
   Keys match the state codes in map-data.js.

   Telangana (2014) and Ladakh (2019) have their own outlines now — tools/map-split.py
   cut the internal line without touching the national boundary — so they are full states
   here rather than the `pending` entries they used to be. `pending` is kept as a seam,
   empty, for the next reorganisation. Renamed states use their modern names. */

window.IND_GEO = {
  states: {
    AN: { name: 'Andaman & Nicobar Islands', type: 'ut', capital: 'Port Blair',
          fact: 'Islands so far out to sea they are closer to Myanmar than to India, with rainforest and coral reefs.',
          food: 'Fish curry with coconut' },
    AP: { name: 'Andhra Pradesh', capital: 'Amaravati',
          fact: 'Home of Tirupati, one of the busiest temples on Earth, and of some of the hottest food in India.',
          food: 'Pulihora', note: 'Telangana was carved out of this state in 2014.' },
    LA: { name: 'Ladakh', type: 'ut', capital: 'Leh',
          fact: 'A cold desert high in the mountains, where the air is thin, the sky is enormous and Buddhist monasteries sit on the cliffs.',
          food: 'Thukpa', note: 'Became a union territory of its own in 2019.' },
    TG: { name: 'Telangana', capital: 'Hyderabad',
          fact: 'The Charminar, the Golconda fort, and a biryani people argue about across the whole country.',
          food: 'Hyderabadi biryani', note: 'Carved out of Andhra Pradesh in 2014.' },
    AR: { name: 'Arunachal Pradesh', capital: 'Itanagar',
          fact: 'The sun rises here first in all of India — the name means "land of the dawn-lit mountains".',
          food: 'Thukpa' },
    AS: { name: 'Assam', capital: 'Dispur',
          fact: 'Tea gardens, the mighty Brahmaputra, and the one-horned rhinos of Kaziranga.',
          food: 'Masor tenga' },
    BR: { name: 'Bihar', capital: 'Patna',
          fact: 'The Buddha found enlightenment here at Bodh Gaya, and Nalanda was one of the first universities in the world.',
          food: 'Litti chokha' },
    CH: { name: 'Chandigarh', type: 'ut', capital: 'Chandigarh',
          fact: 'A whole city designed from scratch, sector by sector, in the 1950s.',
          food: 'Chole bhature' },
    CT: { name: 'Chhattisgarh', capital: 'Raipur',
          fact: 'Deep forests, waterfalls, and some of the oldest rock paintings in India.',
          food: 'Chila' },
    DD: { name: 'Daman & Diu', type: 'ut', capital: 'Daman',
          fact: 'Portuguese forts on the sea. Merged with Dadra & Nagar Haveli in 2020.',
          food: 'Seafood' },
    DL: { name: 'Delhi', type: 'ut', capital: 'New Delhi',
          fact: 'India\'s capital, and a city that has been built and rebuilt at least seven times.',
          food: 'Chaat' },
    DN: { name: 'Dadra & Nagar Haveli', type: 'ut', capital: 'Silvassa',
          fact: 'Small, green, and home to Warli painting — the white stick figures on red earth.',
          food: 'Ubadiyu' },
    GA: { name: 'Goa', capital: 'Panaji',
          fact: 'Beaches, Portuguese churches and the smallest state in India.',
          food: 'Fish curry rice' },
    GJ: { name: 'Gujarat', capital: 'Gandhinagar',
          fact: 'Gandhi was born here. So were the Asiatic lions of Gir — the only wild lions left in Asia.',
          food: 'Dhokla' },
    HP: { name: 'Himachal Pradesh', capital: 'Shimla',
          fact: 'Apple orchards, snow peaks, and Dharamshala, home of the Dalai Lama.',
          food: 'Siddu' },
    HR: { name: 'Haryana', capital: 'Chandigarh',
          fact: 'Wheat fields, wrestling akharas, and Kurukshetra — where the Mahabharata war is set.',
          food: 'Bajra khichdi' },
    JH: { name: 'Jharkhand', capital: 'Ranchi',
          fact: 'Forests and waterfalls, and more of India\'s coal and iron than anywhere else.',
          food: 'Dhuska' },
    JK: { name: 'Jammu & Kashmir', capital: 'Srinagar (summer) · Jammu (winter)',
          fact: 'Houseboats on Dal Lake, saffron fields, and the Himalaya at their highest.',
          food: 'Rogan josh', note: 'Ladakh became a separate union territory in 2019.' },
    KA: { name: 'Karnataka', capital: 'Bengaluru',
          fact: 'The stone city of Hampi, coffee hills, and India\'s software capital.',
          food: 'Bisi bele bath' },
    KL: { name: 'Kerala', capital: 'Thiruvananthapuram',
          fact: 'Backwaters, spice ports that traded with Rome, and one of the oldest churches and synagogues in India.',
          food: 'Sadya' },
    LD: { name: 'Lakshadweep', type: 'ut', capital: 'Kavaratti', marker: true,
          fact: 'Thirty-six coral islands in the Arabian Sea — India\'s smallest territory.',
          food: 'Tuna and coconut' },
    MH: { name: 'Maharashtra', capital: 'Mumbai',
          fact: 'The Ajanta and Ellora caves, Shivaji\'s hill forts, and the busiest city in India.',
          food: 'Puran poli' },
    ML: { name: 'Meghalaya', capital: 'Shillong',
          fact: 'The wettest place on Earth, and bridges grown from living tree roots.',
          food: 'Jadoh' },
    MN: { name: 'Manipur', capital: 'Imphal',
          fact: 'Loktak Lake has floating islands of grass big enough to stand on.',
          food: 'Eromba' },
    MP: { name: 'Madhya Pradesh', capital: 'Bhopal',
          fact: 'The heart of India — Sanchi\'s great stupa, Khajuraho\'s carvings, and tiger forests.',
          food: 'Poha' },
    MZ: { name: 'Mizoram', capital: 'Aizawl',
          fact: 'Bamboo hills, and a bamboo dance you have to leap through without getting caught.',
          food: 'Bai' },
    NL: { name: 'Nagaland', capital: 'Kohima',
          fact: 'Sixteen major tribes, each with its own language, and the Hornbill Festival every December.',
          food: 'Smoked pork with bamboo shoot' },
    OR: { name: 'Odisha', capital: 'Bhubaneswar',
          fact: 'The Sun Temple at Konark is built as a giant stone chariot. Pattachitra painting comes from here.',
          food: 'Dalma' },
    PB: { name: 'Punjab', capital: 'Chandigarh',
          fact: 'The Golden Temple at Amritsar serves free food to everyone who comes — tens of thousands a day.',
          food: 'Sarson da saag' },
    PY: { name: 'Puducherry', type: 'ut', capital: 'Puducherry',
          fact: 'French street names, yellow houses, and a promenade by the sea.',
          food: 'Dosa with French bread' },
    RJ: { name: 'Rajasthan', capital: 'Jaipur',
          fact: 'The Thar desert, forts on every hill, and the Aravalli — mountains older than the Himalaya.',
          food: 'Dal baati churma' },
    SK: { name: 'Sikkim', capital: 'Gangtok',
          fact: 'India\'s first fully organic state, under Kanchenjunga, the third-highest mountain on Earth.',
          food: 'Momos' },
    TN: { name: 'Tamil Nadu', capital: 'Chennai',
          fact: 'Temple towers you can see from miles away, Chola bronzes, and the oldest living language in India.',
          food: 'Idli sambar' },
    TR: { name: 'Tripura', capital: 'Agartala',
          fact: 'Bamboo forests and the Ujjayanta Palace in the middle of the capital.',
          food: 'Mui borok' },
    UK: { name: 'Uttarakhand', capital: 'Dehradun',
          fact: 'The Ganga and the Yamuna both begin here, in the glaciers.',
          food: 'Kafuli' },
    UP: { name: 'Uttar Pradesh', capital: 'Lucknow',
          fact: 'The Taj Mahal, Varanasi on the Ganga, and more people than almost any country in the world.',
          food: 'Tunday kebab / peda' },
    WB: { name: 'West Bengal', capital: 'Kolkata',
          fact: 'The Sundarbans mangroves, where tigers swim, and Durga Puja, when the whole city becomes a gallery.',
          food: 'Macher jhol' }
  },

  /* States that exist today but have no separate outline in the shipped geometry. Empty
     since Telangana and Ladakh were cut out properly — kept as the seam for the next one,
     so a state without geometry is still NAMED rather than silently missing. */
  pending: [],

  rivers: [
    { id: 'ganga',       name: 'Ganga',       from: 'Gangotri glacier',  to: 'Bay of Bengal', states: ['UK','UP','BR','WB'], fact: 'India\'s most sacred river, and home to a rare freshwater dolphin.' },
    { id: 'yamuna',      name: 'Yamuna',      from: 'Yamunotri',         to: 'joins the Ganga at Prayagraj', states: ['UK','HR','DL','UP'], fact: 'The Taj Mahal stands on its bank.' },
    { id: 'brahmaputra', name: 'Brahmaputra', from: 'Tibet',             to: 'Bay of Bengal', states: ['AR','AS'], fact: 'So wide in Assam that you sometimes cannot see the far bank.' },
    { id: 'godavari',    name: 'Godavari',    from: 'Trimbakeshwar',     to: 'Bay of Bengal', states: ['MH','AP'], fact: 'The longest river of peninsular India — the "Dakshina Ganga".' },
    { id: 'kaveri',      name: 'Kaveri',      from: 'Talakaveri',        to: 'Bay of Bengal', states: ['KA','TN'], fact: 'The river the Chola empire was built on.' },
    { id: 'narmada',     name: 'Narmada',     from: 'Amarkantak',        to: 'Arabian Sea',   states: ['MP','GJ'], fact: 'One of the few big Indian rivers that flows west, not east.' },
    { id: 'indus',       name: 'Indus',       from: 'Tibet',             to: 'Arabian Sea',   states: ['JK'], fact: 'India is named after it. The Harappan cities grew along it.' }
  ],

  monuments: [
    { id: 'taj',      name: 'Taj Mahal',            state: 'UP', when: '1653',        badge: 'itihaas', fact: 'Built by Shah Jahan for Mumtaz Mahal. It changes colour with the light.' },
    { id: 'qutub',    name: 'Qutub Minar',          state: 'DL', when: '1199–1220',   badge: 'itihaas', fact: 'The tallest brick minaret in the world, with an iron pillar beside it that has barely rusted in 1,600 years.' },
    { id: 'hampi',    name: 'Hampi',                state: 'KA', when: '14th–16th c.',badge: 'itihaas', fact: 'The capital of Vijayanagara — a city of stone chariots and boulders.' },
    { id: 'konark',   name: 'Konark Sun Temple',    state: 'OR', when: '13th c.',     badge: 'itihaas', fact: 'Built as a chariot for the sun god, with 24 carved stone wheels that work as sundials.' },
    { id: 'sanchi',   name: 'Sanchi Stupa',         state: 'MP', when: 'c. 250 BCE',  badge: 'itihaas', fact: 'Begun by Ashoka. Jataka tales are carved on its gateways.' },
    { id: 'ajanta',   name: 'Ajanta & Ellora Caves',state: 'MH', when: '2nd c. BCE–',  badge: 'itihaas', fact: 'Whole temples cut downwards out of a single cliff of rock.' },
    { id: 'golden',   name: 'Harmandir Sahib',      state: 'PB', when: '1589',        badge: 'aaj',     fact: 'The Golden Temple has four doors, one on each side, so anyone may enter from any direction.' },
    { id: 'meenakshi',name: 'Meenakshi Temple',     state: 'TN', when: '17th c.',     badge: 'aaj',     fact: 'Fourteen towers covered in thousands of painted figures.' },
    { id: 'ranakpur', name: 'Ranakpur Jain Temple', state: 'RJ', when: '15th c.',     badge: 'aaj',     fact: '1,444 marble pillars, and no two of them are carved the same.' },
    { id: 'khajuraho',name: 'Khajuraho',            state: 'MP', when: '950–1050',    badge: 'itihaas', fact: 'Temples covered in carvings of everyday life a thousand years ago.' },
    { id: 'charminar',name: 'Charminar',            state: 'AP', when: '1591',        badge: 'itihaas', fact: 'Four minarets over a crossroads in the middle of Hyderabad.' },
    { id: 'gateway',  name: 'Gateway of India',     state: 'MH', when: '1924',        badge: 'itihaas', fact: 'The last British troops left India through this arch in 1948.' }
  ],

  /* pin positions in the 1000x1100 map frame */
  pins: {
    taj: [430, 300], qutub: [385, 285], hampi: [390, 760], konark: [640, 620],
    sanchi: [400, 470], ajanta: [345, 585], golden: [318, 190], meenakshi: [400, 930],
    ranakpur: [265, 400], khajuraho: [455, 425], charminar: [430, 730], gateway: [285, 640]
  }
};
