/* Bizzing India — photo credits. GENERATED by tools/fetch-photos.py — do not hand-edit.
   Freely-licensed photographs from Wikimedia Commons; every entry
   carries author, license and source. An image without its credit
   row must not ship (CLAUDE.md; enforced by `fetch-photos.py verify`). */

window.IND_PHOTO_CREDITS = {
};
