#!/usr/bin/env node
/* Bizzing India — Naksha's neighbours, computed from the map's own geometry (games spec §4.3, N5).

   Nobody types "Madhya Pradesh touches Gujarat". Two states are neighbours here when their
   outlines in app/map-data.js — the Survey of India depiction, J&K whole — run alongside each
   other for a real stretch: every edge of one state is sampled every half unit, and a sample
   counts as shared when it lies within EPS of the other state's outline. A stretch shorter
   than MIN_SHARED units is a corner touch, not a border, and is dropped (the map was simplified
   per state, so two states that meet at a point can graze each other for a unit or so).

   Output: app/data-naksha.js → window.IND_NAKSHA = { neighbours: { CODE: [codes…] }, … }.
   The same function is exported for tools/check-naksha.js, which recomputes it from the
   geometry and fails if the shipped file differs by a single pair.

   Run:  node tools/build-naksha.js          # writes app/data-naksha.js
         node tools/build-naksha.js --print  # prints the table, writes nothing */
const fs = require('fs');
const path = require('path');

const APP = path.join(__dirname, '..', 'app');
const EPS = 1.2;          /* map units (the frame is 1000 × 1100): how close counts as the same line */
const STEP = 0.5;         /* sample spacing along every edge */
const MIN_SHARED = 3;     /* units of shared outline below which two states only touch at a corner */

function loadMap() {
  const src = fs.readFileSync(path.join(APP, 'map-data.js'), 'utf8');
  const window = {};
  new Function('window', src)(window);
  return window.IND_MAP;
}

/* "M x,y x,y … Z M …" → rings of [x, y] */
function rings(d) {
  const out = [];
  String(d).split(/M/).forEach(part => {
    const nums = (part.match(/-?\d+(?:\.\d+)?/g) || []).map(Number);
    const ring = [];
    for (let i = 0; i + 1 < nums.length; i += 2) ring.push([nums[i], nums[i + 1]]);
    if (ring.length > 1) out.push(ring);
  });
  return out;
}

function segments(rs) {
  const segs = [];
  rs.forEach(r => { for (let i = 0; i < r.length; i++) segs.push([r[i], r[(i + 1) % r.length]]); });
  return segs;
}

function box(segs) {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  segs.forEach(([a, b]) => { x0 = Math.min(x0, a[0], b[0]); y0 = Math.min(y0, a[1], b[1]); x1 = Math.max(x1, a[0], b[0]); y1 = Math.max(y1, a[1], b[1]); });
  return [x0, y0, x1, y1];
}

function distSeg(p, a, b) {
  const dx = b[0] - a[0], dy = b[1] - a[1], L = dx * dx + dy * dy;
  let t = L ? ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / L : 0;
  t = Math.max(0, Math.min(1, t));
  const x = a[0] + t * dx - p[0], y = a[1] + t * dy - p[1];
  return Math.sqrt(x * x + y * y);
}

/* how many units of A's outline lie within EPS of B's */
function sharedLength(segA, segB, bbB) {
  let n = 0;
  for (const [a, b] of segA) {
    const len = Math.hypot(b[0] - a[0], b[1] - a[1]);
    if (Math.max(a[0], b[0]) < bbB[0] - EPS || Math.min(a[0], b[0]) > bbB[2] + EPS ||
        Math.max(a[1], b[1]) < bbB[1] - EPS || Math.min(a[1], b[1]) > bbB[3] + EPS) continue;
    const k = Math.max(1, Math.ceil(len / STEP));
    for (let i = 0; i < k; i++) {
      const t = (i + 0.5) / k, p = [a[0] + t * (b[0] - a[0]), a[1] + t * (b[1] - a[1])];
      if (p[0] < bbB[0] - EPS || p[0] > bbB[2] + EPS || p[1] < bbB[1] - EPS || p[1] > bbB[3] + EPS) continue;
      for (const [c, d] of segB) if (distSeg(p, c, d) <= EPS) { n += len / k; break; }
    }
  }
  return n;
}

function computeNeighbours(M) {
  M = M || loadMap();
  const codes = Object.keys(M.paths).sort();
  const segs = {}, bb = {};
  codes.forEach(c => { segs[c] = segments(rings(M.paths[c])); bb[c] = box(segs[c]); });
  const nb = {}, shared = {};
  codes.forEach(c => { nb[c] = []; });
  for (let i = 0; i < codes.length; i++) for (let j = i + 1; j < codes.length; j++) {
    const a = codes[i], b = codes[j], A = bb[a], B = bb[b];
    if (A[2] < B[0] - EPS || B[2] < A[0] - EPS || A[3] < B[1] - EPS || B[3] < A[1] - EPS) continue;
    const L = Math.min(sharedLength(segs[a], segs[b], B), sharedLength(segs[b], segs[a], A));
    if (L >= MIN_SHARED) { nb[a].push(b); nb[b].push(a); shared[a + '-' + b] = Math.round(L * 10) / 10; }
  }
  codes.forEach(c => nb[c].sort());
  return { neighbours: nb, shared };
}

function fileText(res) {
  return '/* Bizzing India — Naksha\'s neighbours. GENERATED by tools/build-naksha.js from the\n' +
    '   outlines in map-data.js (the Survey of India depiction, J&K whole): two states are\n' +
    '   neighbours when their outlines run together for at least ' + MIN_SHARED + ' map units. Never typed —\n' +
    '   change the map, rerun the tool; tools/check-naksha.js recomputes this and must agree. */\n' +
    'window.IND_NAKSHA = ' + JSON.stringify({ rule: { eps: EPS, step: STEP, minShared: MIN_SHARED }, neighbours: res.neighbours }) + ';\n';
}

module.exports = { computeNeighbours, fileText, loadMap, rings };

if (require.main === module) {
  const res = computeNeighbours();
  if (process.argv.includes('--print')) {
    Object.keys(res.neighbours).forEach(c => console.log(c.padEnd(3), res.neighbours[c].join(' ')));
    console.log(res.shared);
  } else {
    fs.writeFileSync(path.join(APP, 'data-naksha.js'), fileText(res));
    console.log('wrote app/data-naksha.js —', Object.keys(res.neighbours).length, 'territories,',
      Object.keys(res.shared).length, 'shared borders');
  }
}
