#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""One painted picture per Bhugol feature — the fallback behind real photos.

ILLUSTRATIONS in the app's picture-book gouache, tagged as paintings in the
UI. Real photographs (tools/fetch-city-photos.py --bhugol) take precedence the
moment their manifest has an entry. Resume-safe: existing files are skipped,
and the manifest is rewritten every ten pictures so partial runs ship.

    export GEMKEY=...
    python3 tools/gen-bhugol-art.py [--only id] [--state XX] [--model m]
"""
import argparse, io, json, os, re, sys, time, base64, urllib.request
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.join(HERE, "..", "app")
OUT = os.path.join(APP, "art", "bhugol")
W, H, Q = 720, 405, 72
DEFAULT_MODEL = "gemini-3.1-flash-image"

STYLE = (" Flat hand-painted Indian illustration, matte gouache texture, warm "
         "children's picture-book art, wide 16:9 landscape, rich colour, soft "
         "light. Any people tiny and distant, no faces. No deities or figures "
         "of worship. Absolutely NO text, NO letters, NO numerals, NO logos, "
         "NO watermark, NO border, NO frame.")
TYPE_HINT = {
    'river': 'a wide river landscape', 'lake': 'a calm lake landscape', 'wetland': 'a wetland full of birds',
    'falls': 'a great waterfall', 'park': 'a wildlife forest landscape', 'range': 'a hill landscape',
    'peak': 'a high mountain peak', 'desert': 'a desert landscape', 'glacier': 'a glacier in high mountains',
    'pass': 'a high mountain pass road', 'cave': 'a cave entrance in rock', 'island': 'an island in the sea',
    'coast': 'a beach and coastline', 'spring': 'a natural spring pool',
}
STATE = {'JK':'Jammu and Kashmir','LA':'Ladakh','HP':'Himachal Pradesh','PB':'Punjab','HR':'Haryana','UK':'Uttarakhand',
 'UP':'Uttar Pradesh','BR':'Bihar','JH':'Jharkhand','WB':'West Bengal','SK':'Sikkim','AR':'Arunachal Pradesh','NL':'Nagaland',
 'MN':'Manipur','MZ':'Mizoram','TR':'Tripura','ML':'Meghalaya','AS':'Assam','OR':'Odisha','CT':'Chhattisgarh','MP':'Madhya Pradesh',
 'RJ':'Rajasthan','GJ':'Gujarat','MH':'Maharashtra','GA':'Goa','KA':'Karnataka','KL':'Kerala','TN':'Tamil Nadu','AP':'Andhra Pradesh',
 'TG':'Telangana','DL':'Delhi','CH':'Chandigarh','PY':'Puducherry','AN':'the Andaman and Nicobar Islands','LD':'Lakshadweep',
 'DN':'Dadra and Nagar Haveli','DD':'Daman and Diu'}


def load_features():
    s = io.open(os.path.join(APP, "data-bhugol.js"), encoding="utf-8").read()
    body = s[s.index("features: [") + len("features: ["):]
    body = body[:body.rindex("]")]
    return [json.loads(l.strip().rstrip(",")) for l in body.strip().splitlines() if l.strip().startswith("{")]


def generate(prompt, key, model):
    url = "https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s" % (model, key)
    body = json.dumps({"contents": [{"parts": [{"text": prompt}]}],
                       "generationConfig": {"responseModalities": ["IMAGE"], "imageConfig": {"aspectRatio": "16:9"}}}).encode()
    req = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(req, timeout=180) as r:
                data = json.load(r)
            for part in data["candidates"][0]["content"]["parts"]:
                blob = part.get("inlineData") or part.get("inline_data")
                if blob:
                    return base64.b64decode(blob["data"])
            raise RuntimeError("no image part")
        except Exception:
            if attempt == 3:
                raise
            time.sleep(4 * (attempt + 1))


def save(raw, sid):
    im = Image.open(io.BytesIO(raw)).convert("RGB")
    w, h = im.size; t = W / H
    if w / h > t:
        nw = int(round(h * t)); im = im.crop(((w - nw) // 2, 0, (w - nw) // 2 + nw, h))
    elif w / h < t:
        nh = int(round(w / t)); im = im.crop((0, (h - nh) // 2, w, (h - nh) // 2 + nh))
    im = im.resize((W, H), Image.LANCZOS)
    os.makedirs(OUT, exist_ok=True)
    im.save(os.path.join(OUT, sid + ".jpg"), "JPEG", quality=Q, optimize=True, progressive=True)


def write_manifest():
    have = sorted(f[:-4] for f in os.listdir(OUT) if f.endswith(".jpg")) if os.path.isdir(OUT) else []
    with io.open(os.path.join(APP, "bhugol-art-manifest.js"), "w", encoding="utf-8") as f:
        f.write("/* generated by tools/gen-bhugol-art.py — paintings, not photographs; do not edit */\n")
        f.write("window.IND_BHUGOL_ART = %s;\n" % json.dumps(have))
    return len(have)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only"); ap.add_argument("--state"); ap.add_argument("--model", default=DEFAULT_MODEL)
    a = ap.parse_args()
    key = os.environ.get("GEMKEY")
    if not key:
        sys.exit("GEMKEY not set")
    feats = load_features()
    if a.only: feats = [x for x in feats if x["id"] == a.only]
    if a.state: feats = [x for x in feats if x["st"] == a.state]
    done = 0
    for i, ft in enumerate(feats):
        path = os.path.join(OUT, ft["id"] + ".jpg")
        if os.path.exists(path):
            continue
        prompt = ("%s: %s, in %s, India. Scene: %s" % (TYPE_HINT.get(ft["t"], "a landscape"), ft["n"],
                  STATE.get(ft["st"], "India"), ft["f"]) + STYLE)
        try:
            save(generate(prompt, key, a.model), ft["id"])
            done += 1
            print("ok   %s" % ft["id"], flush=True)
        except Exception as e:
            print("FAIL %s %s" % (ft["id"], e), flush=True)
        if done % 10 == 0:
            write_manifest()
    print("manifest: %d paintings" % write_manifest())


if __name__ == "__main__":
    main()
