#!/usr/bin/env python3
"""gen-art-manifest.py — rebuild app/art-manifest.js from the PNGs actually on disk.

app/art-manifest.js says at the top that it is generated by scanning app/art/*.png.
That was aspirational: nothing generated it, it was maintained by hand, and it drifted
eighteen ids behind the moment a batch of avatars landed. An id missing from the
manifest silently loses its painted tile and falls back to the inline SVG (or to
nothing at all, which verify.js catches as "a registry that promises nothing").

This makes the header true. Run it after any gen-avatars.py batch:

    python3 tools/gen-art-manifest.py

Writes nothing and exits 1 if the manifest would be unchanged in content but the file
is missing, so it is safe to run from a build script.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "app", "art")
OUT = os.path.join(ROOT, "app", "art-manifest.js")

HEADER = """/* Bizzing India — art manifest. GENERATED by tools/gen-art-manifest.py; do not hand-edit.
   The old header credited gen-avatars.py, which never actually wrote this file — it was
   maintained by hand and drifted 18 ids behind the moment a batch landed. Rebuilding it
   from the PNGs on disk is the only version that cannot lie.
   Ids listed here have a real raster avatar at app/art/<id>.png (256x256).
   Anything not listed falls back to the inline SVG in app/avatars.js. */

window.IND_ART_IMG = [
"""


def main():
    if not os.path.isdir(ART):
        sys.exit("no app/art directory at " + ART)

    ids = sorted(
        os.path.splitext(f)[0]
        for f in os.listdir(ART)
        if f.endswith(".png") and not f.startswith(".")
    )
    if not ids:
        sys.exit("app/art holds no PNGs — refusing to write an empty manifest")

    # six per line, matching the file's existing shape so the diff stays readable
    lines = []
    for i in range(0, len(ids), 6):
        chunk = ", ".join("'" + x + "'" for x in ids[i:i + 6])
        lines.append("  " + chunk + ",")
    body = "\n".join(lines).rstrip(",")

    before = ""
    if os.path.exists(OUT):
        before = open(OUT, encoding="utf-8").read()
    text = HEADER + body + "\n];\n"

    if text == before:
        print("art-manifest.js already lists all %d tiles — unchanged" % len(ids))
        return

    was = len(re.findall(r"'[^']+'", before))
    open(OUT, "w", encoding="utf-8").write(text)
    print("art-manifest.js rebuilt: %d tiles (was %d)" % (len(ids), was))


if __name__ == "__main__":
    main()
