#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Where each drawn piece actually stands.

The board anchors a piece on the SOUTH VERTEX of its footprint and, until
now, assumed that vertex was the bottom-centre of the artwork. It is not.
A model draws the object wherever it likes in the frame and puts a water pot,
a coil of rope or a scatter of ground beside it, so the lowest painted pixel
is often not the building's foot at all — and the building ends up hovering
up and to one side of its own cell.

This measures the foot instead of assuming it. For a box seen in three-quarter
view the base is a diamond, and the widest opaque row in the lower part of the
picture is that diamond's east-west axis. Its south vertex sits a quarter of
that width below it, and its centre is the middle of that row. Both are
recorded per face, as an offset from the artwork's own bottom-centre, so the
board can put the foot on the vertex and be done with it.

    python3 tools/kit-feet.py [--only id]

Writes app/kit-feet-manifest.js:  id -> [[dx, dy] x 4], in artwork pixels.
  dx  how far the foot is right of the artwork's horizontal centre
  dy  how far the foot is ABOVE the artwork's bottom edge
"""
import argparse, io, json, os
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "app", "art", "kit")
OUT = os.path.join(ROOT, "app", "kit-feet-manifest.js")


def foot(path, band=0.11, minrun=0.14):
    """Where the drawing touches the ground, and HOW WIDE it is there.

    The width is the part that mattered and was missed for three rounds. A
    piece was scaled so its whole bounding box spanned the cell — but that box
    includes the roof overhang, which is wider than the walls, and the sky
    above the roof. So the building's actual base came out smaller than the
    diamond it stood on, sat somewhere inside it, and left a crescent of bare
    cell showing on the low side. That crescent is what reads as floating.

    So: take the bottom slice of the drawing, cut it into contiguous runs, drop
    anything narrower than a seventh of the picture (a rope, a pot, a stray
    speck), and what is left is the building on the ground. Its width is the
    base width; its middle is where the piece stands; the lowest opaque row is
    the foot.
    """
    im = Image.open(path).convert("RGBA")
    al = np.asarray(im)[:, :, 3] > 40
    h, w = al.shape
    ys, xs = np.where(al)
    if not len(ys):
        return [0.0, 0.0, float(w)]
    bottom = int(ys.max())
    cut = max(0, bottom - max(2, int(h * band)))
    slab = al[cut:bottom + 1].any(axis=0)

    runs, start = [], None
    for x in range(w):
        if slab[x] and start is None:
            start = x
        elif not slab[x] and start is not None:
            runs.append((start, x - 1)); start = None
    if start is not None:
        runs.append((start, w - 1))
    wide = [r for r in runs if (r[1] - r[0] + 1) >= w * minrun]
    if not wide:
        wide = [max(runs, key=lambda r: r[1] - r[0])] if runs else [(0, w - 1)]
    x0, x1 = min(r[0] for r in wide), max(r[1] for r in wide)
    bw = float(x1 - x0 + 1)
    cx = (x0 + x1) / 2.0
    return [round(cx - w / 2.0, 1), round(float((h - 1) - bottom), 1), round(bw, 1)]


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--only")
    args = ap.parse_args()
    out = {}
    ids = [args.only] if args.only else sorted(os.listdir(ART))
    for pid in ids:
        d = os.path.join(ART, pid)
        if not os.path.isdir(d) or not os.path.exists(os.path.join(d, "0.png")):
            continue
        faces = []
        for i in range(4):
            f = os.path.join(d, "%d.png" % i)
            faces.append(foot(f) if os.path.exists(f) else [0.0, 0.0, 64.0])
        # TRUST, THEN VERIFY. Four views of one object cannot disagree about
        # how wide its base is. Where they do, the measurement has caught a
        # rope or a leg or a soft matte edge rather than the building, and a
        # wrong correction is worse than none: those parts keep the plain
        # bounding-box placement they had. Only agreement is believed.
        bws = sorted(f[2] for f in faces)
        med = bws[len(bws) // 2]
        dys = [f[1] for f in faces]
        ok = (med > 0
              and all(abs(f[2] - med) <= med * 0.22 for f in faces)
              and max(dys) <= 8
              and all(abs(f[0]) <= 0.34 * med for f in faces))
        if ok:
            out[pid] = faces
    with io.open(OUT, "w", encoding="utf-8") as f:
        f.write("/* generated by tools/kit-feet.py — where each drawn piece\n"
                "   actually stands. id -> [[dx,dy] x 4] in artwork pixels:\n"
                "   dx right of the artwork's centre, dy above its bottom edge,\n"
                "   bw the width of the base itself — not of the bounding box.\n"
                "   Measured, not assumed. Do not edit by hand. */\n")
        f.write("window.IND_KIT_FEET = %s;\n" % json.dumps(out, sort_keys=True))
    print("%d parts of %d have a base all four views agree on" % (len(out), len(ids)))
    for pid in ("hs-har-room", "wa-har-well", "bd-har-store", "hs-har-court"):
        if pid in out:
            print("  %-16s %s" % (pid, out[pid]))


if __name__ == "__main__":
    main()
