#!/usr/bin/env python3
"""Compute a bounding box per state and rewrite app/map-data.js with M.bbox.

WHY: the map paints each state with its own painting, using an SVG <pattern> per state.
A pattern needs the box it should map the image onto, in user units. Computing that at
runtime with getBBox() means 34 forced layouts on every render of the map view; computing
it once here costs nothing at paint time and the numbers never change unless the geometry
does.

Also verifies that every anchor (the label point already in map-data.js) actually falls
inside its own state, because a label floating in the Bay of Bengal is worse than no label.

Run after any change to the state geometry.
"""
import re
import json
import pathlib

from shapely.geometry import Polygon, MultiPolygon, Point

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'app' / 'map-data.js'


def rings(d):
    """Split a path 'd' into rings of (x, y). The generator that wrote these emits
    'M x,y x,y x,y' with implicit linetos and one M per ring, so a split on M is enough —
    there are no curves or relative commands in this data."""
    out = []
    for chunk in d.split('M'):
        chunk = chunk.strip().rstrip('Zz').strip()
        if not chunk:
            continue
        nums = [float(n) for n in re.findall(r'-?\d+\.?\d*', chunk)]
        pts = list(zip(nums[0::2], nums[1::2]))
        if len(pts) >= 3:
            out.append(pts)
    return out


def shape(d):
    polys = []
    for r in rings(d):
        p = Polygon(r)
        if not p.is_valid:
            p = p.buffer(0)
        if not p.is_empty and p.area > 0:
            polys.append(p)
    if not polys:
        return None
    return polys[0] if len(polys) == 1 else MultiPolygon(
        [g for p in polys for g in (p.geoms if isinstance(p, MultiPolygon) else [p])])


src = SRC.read_text(encoding='utf-8')
paths = dict(re.findall(r'\n\s*([A-Z]{2}):\s*[\'"]([^\'"]+)[\'"]', src))
# Keys in map-data.js are bare JS identifiers, not JSON, so pull the pairs out directly
# rather than trying to coerce the block into JSON.
_anchor_block = re.search(r'anchors:\s*\{(.*?)\}\s*[,}]', src, re.S).group(1)
anchors = {c: [float(x), float(y)] for c, x, y in
           re.findall(r'([A-Z]{2})\s*:\s*\[\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\]', _anchor_block)}

bbox, strays = {}, []
for code, d in sorted(paths.items()):
    g = shape(d)
    if g is None:
        continue
    x0, y0, x1, y1 = g.bounds
    bbox[code] = [round(x0, 1), round(y0, 1), round(x1 - x0, 1), round(y1 - y0, 1)]
    a = anchors.get(code)
    if a and not g.buffer(0.5).contains(Point(a)):
        # Fall back to a point guaranteed to be inside the largest piece, so the label
        # sits on the state rather than next to it.
        big = max(g.geoms, key=lambda p: p.area) if isinstance(g, MultiPolygon) else g
        rp = big.representative_point()
        strays.append((code, a, [round(rp.x, 1), round(rp.y, 1)]))

block = ('\n/* Bounding box per state, [x, y, w, h] in viewBox units. GENERATED by\n'
         '   tools/map-bbox.py — the map fills each state with its own painting through an\n'
         '   SVG <pattern>, and a pattern needs the box to map the image onto. Precomputed so\n'
         '   the map view does not force 34 layouts with getBBox() on every render. */\n'
         'window.IND_MAP.bbox = ' + json.dumps(bbox, separators=(',', ':')) + ';\n')

src = re.sub(r'\n/\* Bounding box per state.*?window\.IND_MAP\.bbox = .*?;\n', '\n', src, flags=re.S)
SRC.write_text(src.rstrip() + '\n' + block, encoding='utf-8')

print(f'{len(bbox)} bounding boxes written')
for code, was, now in strays:
    print(f'  anchor outside geometry: {code} {was} -> suggest {now}')
if not strays:
    print('  every anchor sits inside its own state')
