#!/usr/bin/env bash
# Cache-bust every asset URL in app/index.html, and record the build id.
#
# Bizzing Bee's deploy rule, and it exists because we already got caught by it:
# a deploy went out with a new app.js and app.css behind an unchanged ?v= stamp,
# so browsers kept the old files and a whole tab was missing from the nav.
#
# The ?v= stamp cannot bust index.html itself — that is the file that carries the
# stamp, and GitHub Pages serves HTML with its own cache. So we also write the id
# into build.js and show it in the app (Me -> Grown-ups). If someone reports a bug,
# the build id tells you immediately whether they are even looking at your fix.
#
# Run before EVERY gh-pages deploy.
set -euo pipefail
cd "$(dirname "$0")/.."
STAMP="${1:-$(date -u +%Y%m%d%H%M)}"
sed -i -E "s/\?v=[0-9a-zA-Z.]+/?v=${STAMP}/g" app/index.html
# self, not window: this file is importScripts'd by the service worker, where
# window does not exist — in a page, self IS window, so both get the id.
printf "/* generated by tools/stamp.sh — do not hand-edit */\nself.IND_BUILD = '%s';\n" "$STAMP" > app/build.js

# The offline shell and the pack sizes follow the stamp: the service worker's core
# list carries the fresh ?v= urls, and the advertised megabytes stay the truth.
node tools/gen-sw-precache.js
node tools/gen-pack-manifest.js >/dev/null
echo "stamped ?v=${STAMP}"
grep -o '?v=[0-9a-zA-Z.]*' app/index.html | sort -u
