import json, os, base64, urllib.request, time, sys
KEY = os.environ['GKEY']
OUT = '/home/user/bizzingindia.com/app/voice'
VOICE = {
  'en-IN': ('en-IN-Neural2-A', 0.92),   # warm Indian-English storyteller
  'hi-IN': ('hi-IN-Neural2-A', 0.88),   # slower: children imitate these
  'pa-IN': ('pa-IN-Standard-A', 0.88),
}
clips = json.load(open(sys.argv[1]))
done = fail = skip = 0
manifest = []
for c in clips:
    path = os.path.join(OUT, c['key'] + '.mp3')
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path) and os.path.getsize(path) > 500:
        skip += 1; manifest.append(c['key']); continue
    name, rate = VOICE[c['lang']]
    body = json.dumps({
        'input': {'text': c['text']},
        'voice': {'languageCode': c['lang'], 'name': name},
        'audioConfig': {'audioEncoding': 'MP3', 'speakingRate': rate, 'sampleRateHertz': 24000}
    }).encode()
    req = urllib.request.Request(
        'https://texttospeech.googleapis.com/v1/text:synthesize?key=' + KEY,
        data=body, headers={'Content-Type': 'application/json'})
    for attempt in range(4):
        try:
            r = json.load(urllib.request.urlopen(req, timeout=60))
            open(path, 'wb').write(base64.b64decode(r['audioContent']))
            done += 1; manifest.append(c['key']); break
        except Exception as e:
            if attempt == 3:
                fail += 1
                print('FAIL', c['key'], str(e)[:90], flush=True)
            else:
                time.sleep(2 ** attempt)
    if (done + skip) % 25 == 0:
        print('  ...', done + skip, '/', len(clips), flush=True)

with open(os.path.join(OUT, '..', 'voice-manifest.js'), 'w') as f:
    f.write('/* Bizzing India - bundled narration index. Generated by tools/tts.py.\n'
            '   English story narration: en-IN-Neural2-A. Hindi/Punjabi letters and words are\n'
            '   TTS placeholders - per docs/09 these MUST be replaced with human voice before\n'
            '   launch, because children imitate them. */\n')
    f.write('window.IND_VOICE = ' + json.dumps(sorted(manifest), ensure_ascii=False) + ';\n')
print('DONE new=%d cached=%d failed=%d total=%d' % (done, skip, fail, len(clips)))
